Урока 2
IlyaOrlov/PythonCourse2.0_August22 pull request #16
Opened 2022-09-01 14:21 UTC by NazGuJl

Задания 1, 2 , 3

2022-09-01 18:21 UTC, IlyaOrlov requested changes
Хорошо, но есть пара замечаний)

2022-09-01 18:21 UTC, IlyaOrlov commented on Practice/LukichevI/day_2_task_3.py
> +          mp3s = []    # больше 4 пробелов
Здесь и ниже в аналогичных случаях лучше сформулировать ошибку, как "нарушение уровней вложенности". Потому что просто использование, к примеру, 5 пробелов вместо 4-х будет только нарушением стиля, но интерпретатор такой код вполне переварит. Здесь же даже интерпретатор не поймёт, какой код к какому блоку относится.

2022-09-01 18:21 UTC, IlyaOrlov commented on Practice/LukichevI/day_2_task_1.py
> +def square(r):
Согласно [PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Surround%20top%2Dlevel%20function%20and%20class%20definitions%20with%20two%20blank%20lines.) определения функций должны обособляться двумя пустыми строками (т.е. надо поставить по две пустые строки перед строкой 3 и после строки 5). А пустая строка 4 лишняя.

2022-09-02 11:38 UTC, NazGuJl commented
Приветствую. Готов.

2022-09-02 18:03 UTC, IlyaOrlov requested changes
Почти правильно)

2022-09-02 18:03 UTC, IlyaOrlov commented on Practice/LukichevI/day_2_task_1.py
> +def square(r):
Почти правильно) В определение функции входят и стр.5, и стр.8:
```python
def square(r):
    return math.pi * r ** 2
```
Поэтому две пустые строки надо вставить не между выражениями в стр.5 и 8, а после **return math.pi * r ** 2**.

2022-09-04 19:45 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-04 19:45 UTC, merged