Moiseev dmitry
IlyaOrlov/PythonCourse2.0_August22 pull request #17
Opened 2022-09-01 19:55 UTC by moisdima

урок 2  задание 3

2022-09-02 06:31 UTC, IlyaOrlov requested changes
В целом, всё хорошо. Только файлы с решениями надо поместить в свою папку внутри папки Practice!

2022-09-02 06:31 UTC, IlyaOrlov commented on lesson_2_2.py
> +result = (int(diff) / int(distance))*100
Здесь int(diff) делать излишне, т.к. diff в строке 5 определен, как разность целых чисел, т.е. автоматически является числом.

2022-09-02 06:31 UTC, IlyaOrlov commented on lesson_2_2.py
> +
В чем смысл пустых строк здесь и в стр. 6 и 8?

2022-09-02 06:31 UTC, IlyaOrlov commented on pep8task.py
> +import hashlib  # hash_lib
hashlib и argparse - это названия библиотек, их уже не поменять)

2022-09-02 15:11 UTC, moisdima commented on lesson_2_2.py
> +
исправил

2022-09-02 15:12 UTC, moisdima commented on lesson_2_2.py
> +result = (int(diff) / int(distance))*100
исправил

2022-09-02 15:18 UTC, moisdima commented on pep8task.py
> +import hashlib  # hash_lib
я понял это вчера на уроке)
исправил

2022-09-02 17:54 UTC, IlyaOrlov requested changes
По заданиям только небольшие замечания. 
Глобально замечание такое! Надо перенести все файлы в свою папку. Например, Practice/dmoiseev/lesson_3_1.py

2022-09-02 17:54 UTC, IlyaOrlov commented on Practice/lesson_3_2.py
> +    return (way/time)
Просто так брать результат в скобки (и вообще лишний раз использовать скобки) не стоит. Обычно PyCharm сообщает о лишних скобках предупреждением.

2022-09-02 17:54 UTC, IlyaOrlov commented on Practice/lesson_3_1.py
> +def rectangle(x,y):
Стоит добавить пробел после запятой, как указано в примерах в документации [PEP8](https://peps.python.org/pep-0008/#other-recommendations).
Также внешние скобки в стр.2 лишние.

2022-09-02 17:54 UTC, IlyaOrlov commented on Practice/lesson_2_1.py
> +def square(r):
Согласно [PEP8](https://peps.python.org/pep-0008/#blank-lines:~:text=Surround%20top%2Dlevel%20function%20and%20class%20definitions%20with%20two%20blank%20lines.) определение функции должно быть обособлено двумя пустыми строками (т.е. надо добавить еще по пустой строке перед стр.3 и после стр.4).

2022-09-03 18:58 UTC, IlyaOrlov requested changes
Остались старые замечания, и добавилось несколько новых. Надо исправить!

2022-09-03 18:58 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +def palindrom(list):
list - зарезервированное слово в Python, не стоит его использовать для именования своих переменных (PyCharm тоже подсвечивает такие ошибки).

2022-09-03 18:58 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +    return list == revers(list)
Зачем вызывать функцию, если прямо здесь вместо revers(list) можно написать list[::-1] (только переменную list надо переименовать).
И ещё... А что если пользователь ввёл слово с большой буквы? Например, "Довод". По сути, это тоже палиндром. Но операция "Довод" == "довоД" вернёт False, т.е. Ложь.

2022-09-03 18:58 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +word_list = str(input('Введите слово: '))
str здесь лишняя операция, т.к. input и так всегда возвращает результат типа str (строка).

2022-09-03 18:58 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +if palindrom(word_list):
Раз palindrom возвращает результат логического типа (True или False), то можно сразу печатать этот результат: print(palindrom(word_list))

2022-09-06 19:04 UTC, IlyaOrlov requested changes
Ещё код - ещё комментарии)

2022-09-06 19:04 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_4.py
> +s = str(input('Введиде слово: '))
input и так всегда строку возвращает, поэтому применение str здесь излишне.

2022-09-06 19:04 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_4.py
> +if b != -1 or c != -1:
Можно обойтись и без вспомогательных переменных b и c, подставив find непосредственно в условие. Ну а replace (стр. 7 и 8) стоит внести в тело if: ведь если буква не нашлась, зачем заставлять интерпретатор повторно носиться по строке, пытаясь найти и заменить букву, которой нет (а именно это и делает replace).

2022-09-06 19:04 UTC, IlyaOrlov commented on Practice/MoiseevD/pep8task.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname))  # не хватает скобок (( нижнего подчеркивания has_hname
Наоборот. Достаточно одной открывающей и одной закрывающей скобок.

2022-09-07 18:11 UTC, moisdima commented on Practice/lesson_3_2.py
> +    return (way/time)
Исправил

2022-09-07 18:11 UTC, moisdima commented on Practice/lesson_3_1.py
> +def rectangle(x,y):
Исправил

2022-09-07 18:12 UTC, moisdima commented on Practice/lesson_2_1.py
> +def square(r):
Исправил

2022-09-07 18:12 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +def palindrom(list):
Исправил

2022-09-07 18:12 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +    return list == revers(list)
Исправил

2022-09-07 18:12 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +word_list = str(input('Введите слово: '))
Исправил

2022-09-07 18:13 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +if palindrom(word_list):
Исправил

2022-09-07 18:13 UTC, moisdima commented on Practice/MoiseevD/lesson_3_4.py
> +s = str(input('Введиде слово: '))
Исправил

2022-09-07 18:13 UTC, moisdima commented on Practice/MoiseevD/lesson_3_4.py
> +if b != -1 or c != -1:
Исправил

2022-09-07 18:13 UTC, moisdima commented on Practice/MoiseevD/pep8task.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname))  # не хватает скобок (( нижнего подчеркивания has_hname
Исправил

2022-09-07 20:57 UTC, IlyaOrlov requested changes
Осталась пара замечаний, и одно из них весьма важное!

2022-09-07 20:57 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +if palindrom(low_letters):
Зачем заставлять бедный интерпретатор дважды выполнять функцию palindrom с одними и теми же данными? Строки 7 - 10 можно сократить до print(palindrom(low_letters)),  и будет тот же результат, но достигнутый гораздо меньшими усилиями (особенно, если проверяемая строка очень длинная).

2022-09-07 20:57 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_2_1.py
> +
И после функции тоже должно быть две пустые строки!

2022-09-08 17:52 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +if palindrom(low_letters):
Исправил

2022-09-08 17:52 UTC, moisdima commented on Practice/MoiseevD/lesson_2_1.py
> +
исправил

2022-09-08 19:19 UTC, IlyaOrlov requested changes
Остался последний штрих!

2022-09-08 19:19 UTC, IlyaOrlov commented on Practice/MoiseevD/lesson_3_5.py
> +if True:
Да, но if True зачем оставлять? По этому условию строка 8 и так всегда будет выполняться, так что лучше вообще его удалить.

2022-09-10 11:14 UTC, moisdima commented on Practice/MoiseevD/lesson_3_5.py
> +if True:
Исправил

2022-09-10 12:04 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-10 12:04 UTC, merged