Rybnikov Sergey
IlyaOrlov/PythonCourse2.0_August22 pull request #19
Opened 2022-09-05 17:28 UTC by Kuduzo

Домашнее задание Занятие 3

2022-09-07 20:09 UTC, IlyaOrlov requested changes
Хорошо, но есть некоторые замечания (в основном, по стилю).

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 01.py
> +    return (2*(a+b))
Внешние скобки лишние. Обычно скобки используются в математических выражениях Python для изменения приоритета операций. Просто так их добавлять не нужно, т.к. это ухудшает читабельность.

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 01.py
> +def perimeter(a,b):
Здесь, в определении и при вызове функции (стр. 7) после запятой стоит добавить пробел, также не помешают пробелы вокруг плюса выражении a + b. Строго говоря, PEP8 этого не требует, но все примеры из него написаны именно таким стилем.

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 02.py
> +a=2
Интересно, что здесь делает это выражение)

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 03-01.py
> +    return (print(f"Ваш зашифрованный пароль {encripted_pass}"))
Здесь и в uncoding: не нужно делать return print. 
return используется для возврата значения из функции (функции и возврат значений мы ещё будем проходить).
print используется для вывода на экран. При этом, сама функция print всегда возвращает None.
Можно написать просто print(...) 
Если в функции нет return, она всё равно возвращает None.
Т.е. return print  - это всегда искусственное усложнение кода.

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 04.py
> +txt = str(input("Введите текстовую строку для замены А на *\n"))
str - лишняя: input и так всегда возвращает значение строкового типа.

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 05.py
> +txt = str(input("Проверка на палиндром\nВведите слово\n"))
Здесь тоже str лишняя.

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 05.py
> +if txt.upper() == txt.upper()[::-1]:
Два вызова upper для одной и той же строки. Нужно стараться избегать лишней работы для интерпретатора. Лучше сначала сделать txt = txt.upper(), а потом уже просто сравнивать txt и txt[::-1]

2022-09-07 20:09 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 05.py
> +    print('True')
Почему бы не печатать сразу результат логического выражения: print(txt.upper() == txt.upper()[::-1])? Так короче и проще.

2022-09-08 14:59 UTC, Kuduzo commented on Practice/RybnikovS/Day 03 Task 02.py
> +a=2
Опечатка)

2022-09-08 19:07 UTC, IlyaOrlov requested changes
Почти всё правильно! Всего пара замечаний осталась.

2022-09-08 19:07 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 05.py
> +print(txt.upper() == txt.upper()[::-1])
Не слишком ли много раз upper применяется к одной и той же несчастной строке? Всё-таки upper требует обхода всей строки для получения символов в верхнем регистре, и если строка очень длинная - мы получим лишние тормоза в программе.
Достаточно одного upper, который Вы и так уже сделали в стр.1
Да, я понимаю, что строка 2 - это один в один копия моего комментария, но сам комментарий был о другом. А вот [предыдущий комментарий](https://github.com/IlyaOrlov/PythonCourse2.0_August22/pull/19#discussion_r965227575) как раз был про upper.

2022-09-08 19:07 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 03 Task 02.py
> +speed = avg_speed (distance, fulltime)
Нарушение [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call): лишний пробел после имени функции avg_speed.

2022-09-08 19:36 UTC, Kuduzo commented on Practice/RybnikovS/Day 03 Task 05.py
> +print(txt.upper() == txt.upper()[::-1])
Верно, слишком много. Я понял замечание, исправил в одном месте, а по другое место забыл.  Добавил верхний регистр во время ввода, а вот исправить условие забыл.

2022-09-09 10:14 UTC, IlyaOrlov approved these changes
Отлично!

2022-09-09 10:14 UTC, merged