Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #22
Opened 2022-09-07 07:41 UTC by natalishulgina

2 д/з для 2 лекции

2022-09-07 20:12 UTC, IlyaOrlov requested changes
Всё супер! Только один маленький комментарий.

2022-09-07 20:12 UTC, IlyaOrlov commented on Practice/ShulginaN/lec2_task2.py
> +result = int(diff) / int(distance)
diff и так будет целым числом, потому что определен как разность целых чисел, поэтому приводить его к int не нужно.

2022-09-08 00:19 UTC, natalishulgina commented on Practice/ShulginaN/lec2_task2.py
> +result = int(diff) / int(distance)
Спасибо. Каким образом diff это целое число, если в п. 1,2 мы возвращаем строку?

2022-09-08 07:44 UTC, IlyaOrlov commented on Practice/ShulginaN/lec2_task2.py
> +result = int(diff) / int(distance)
diff определяется не в строках 1,2, а в строке 4 как разность двух int'ов, т.е. двух целых чисел)
При помощи int мы как раз и делаем из start и end числа (точная формулировка: приводим их к типу Число) и потом вычитаем из одного число другое.
Если смотреть по строкам кода, история преобразования типов получится такой:
1. start - строка
2. end - строка
3. distance - строка
4. dif = число(start) - число(end)

2022-09-08 13:55 UTC, natalishulgina commented on Practice/ShulginaN/lec2_task2.py
> +result = int(diff) / int(distance)
Ок, спасибо! Убрала int для diff и добавила комментарий для красивого вывода.
P.S. Подсмотрела, что так можно сделать)

2022-09-08 14:45 UTC, IlyaOrlov approved these changes
Отлично!

2022-09-08 14:45 UTC, merged