Lec 1 Task 1
IlyaOrlov/PythonCourse2.0_August22 pull request #25
Opened 2022-09-07 19:03 UTC by KseniaKatrashova

2022-09-07 21:04 UTC, IlyaOrlov requested changes
Есть замечания! Надо исправить.

2022-09-07 21:04 UTC, IlyaOrlov commented on Practice/Katrashova/task.py
> +ptint(f"Echo:(I)"
Этот код нерабочий! Опечатка в "ptint", неправильные скобки внутри форматной строки, i и I - это разные имена переменных.

2022-09-08 12:14 UTC, KseniaKatrashova commented on Practice/Katrashova/task.py
> +ptint(f"Echo:(I)"
Исправлено

2022-09-08 14:49 UTC, IlyaOrlov commented on Practice/Katrashova/task.py
> +ptint(f"Echo:(I)"
Ну почти... чтоб print(f"Echo:(i)") выводил на экран значение i, а не просто букву i, надо взять её в фигурные скобки, а не в круглые.

2022-09-08 16:14 UTC, KseniaKatrashova commented on Practice/Katrashova/task.py
> +ptint(f"Echo:(I)"
сделано

2022-09-08 18:55 UTC, IlyaOrlov approved these changes
Да, теперь всё ОК)

2022-09-08 18:55 UTC, merged