Lec 2 Tasks 1,2,3
IlyaOrlov/PythonCourse2.0_August22 pull request #26
Opened 2022-09-07 21:50 UTC by Wiwingsy

Не очень понимаю о чём речь в последнем задании в файле pep8task.py  начиная с строки "def parse_arguments(): " (у меня в файле она 52 строка), начиная с неё комментарии не писала.

2022-09-08 07:38 UTC, IlyaOrlov requested changes
Хорошо, но есть замечания.
Что касается pep8task.py... требовалось найти только те ошибки, которые Вам понятны (так-то их там много, хватит на весь курс).
Что же до def parse_arguments(): - в этой функции через библиотеку argparse считываются параметры программы, переданные через командную строку. Мы еще пройдем эту полезную библиотеку.

2022-09-08 07:38 UTC, IlyaOrlov commented on Practice/aturenko/pep8task.py
> +                if file[-3:] == '.mp3': # You must use ".startswith()": if file.startswith('.mp3'):
.startswith() не подойдёт, т.к. здесь проверяются не начало строки, а конец) И в целом данное решение file[-3:] == '.mp3' приемлемое, так что must здесь как-то слишком (should better больше подошло бы).
Аналогично для строки 39.

2022-09-08 07:38 UTC, IlyaOrlov commented on Practice/aturenko/pep8task.py
> +                    mp3s.append({root, file}) # Probably there should be no curly brackets here,
Да, это не dictionary, это множество (set). И криминала в этом нет)

2022-09-08 07:38 UTC, IlyaOrlov commented on Practice/aturenko/pep8task.py
> +            os.rename(path + '/' + hashname, path + '/' + self.map[hashname])) # The path should be
Вот здесь немного не понял... path и так написан "small letters".

2022-09-08 07:38 UTC, IlyaOrlov commented on Practice/aturenko/Homework2.py
> +def square(r):
Определение функции (стр.15-16) должно идти после блока импортов (стр.13) и отделяться от остального кода двумя пустыми строками.

2022-09-08 19:00 UTC, Wiwingsy commented on Practice/aturenko/pep8task.py
> +            os.rename(path + '/' + hashname, path + '/' + self.map[hashname])) # The path should be
Ну тут я имела ввиду, что путь должен быть прописан строчными буквами с подчёркиванием. А здесь идут конструкции с \ в пути.Я так понимаю так нельзя...

2022-09-08 19:00 UTC, Wiwingsy commented on Practice/aturenko/Homework2.py
> +def square(r):
Исправила, добавила описание к функции

2022-09-08 19:08 UTC, Wiwingsy commented on Practice/aturenko/pep8task.py
> +                if file[-3:] == '.mp3': # You must use ".startswith()": if file.startswith('.mp3'):
Да, я пока не очень понимаю это, думала нам надо все недочёты по-максимуму найти) Исправила на should be и .endswith()

2022-09-08 19:11 UTC, Wiwingsy commented on Practice/aturenko/pep8task.py
> +                    mp3s.append({root, file}) # Probably there should be no curly brackets here,
Убрала данный комментарий

2022-09-08 19:14 UTC, IlyaOrlov commented on Practice/aturenko/pep8task.py
> +            os.rename(path + '/' + hashname, path + '/' + self.map[hashname])) # The path should be
"путь должен быть прописан строчными буквами с подчёркиванием" - на чём основано такое понимание?
В PEP8 подобное требование налагается на именование переменных. Участвующие в выражении переменные -  path, hashname, map - вполне этому требованию соответствуют.
Сами же пути к файлам (а их здесь два) формируются динамически, и слэши в путях - это обычное дело. Например: ```IlyaOrlov/PythonCourse2.0_August22/pull/26``` или ```C:\PythonCourseProject2\PythonCourse2.0_August22```.

2022-09-08 19:14 UTC, IlyaOrlov commented on Practice/aturenko/Homework2.py
> +def square(r):
Не вижу исправлений. Видимо, еще не запушили.

2022-09-08 19:58 UTC, Wiwingsy commented on Practice/aturenko/pep8task.py
> +            os.rename(path + '/' + hashname, path + '/' + self.map[hashname])) # The path should be
Ясно, но пока тоже просто не понимаю эту тему с путями видимо. Удалила данный комментарий.

2022-09-09 10:17 UTC, IlyaOrlov approved these changes
Исправления приняты. Теперь всё отлично!

2022-09-09 10:17 UTC, merged