Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #27
Opened 2022-09-08 15:08 UTC by natalishulgina

3 д/з для 2й лекции

2022-09-08 18:54 UTC, IlyaOrlov requested changes
Есть замечания к комментариям)
Кстати, если у Вас есть ещё файлы с решениями, добавляйте их в коммит все сразу. Думаю, так проверка пойдёт быстрее.

2022-09-08 18:54 UTC, IlyaOrlov commented on Practice/ShulginaN/pep8task.py
> +# магический метод или атрибут с двойным подчеркиванием в начале и в конце
"магический метод или атрибут с двойным подчеркиванием в начале и в конце" - это констатация факта)
Но ошибки тут никакой нет.

2022-09-08 18:54 UTC, IlyaOrlov commented on Practice/ShulginaN/pep8task.py
> +# неправильный уровень вложенности
Здесь и в стр.31 - у какого кода неправильный уровень вложенности? 
Конкретно в строках 18 и 32 ошибки с уровнем вложенности нет: эти две функции действительно вложены в класс shuffler (как мы потом узнаем, об этом свидетельствует наличие у них первого аргумента с именем self). 
А вот внутри этих функций с уровнями вложенности действительно творится форменное безобразие!

2022-09-08 18:54 UTC, IlyaOrlov commented on Practice/ShulginaN/pep8task.py
> +# возможно, должно быть так: import time
Да, даже без "возможно")

2022-09-09 12:03 UTC, natalishulgina commented on Practice/ShulginaN/pep8task.py
> +# магический метод или атрибут с двойным подчеркиванием в начале и в конце
Ок, спасибо. Я подумала, что это ошибка)

2022-09-09 23:20 UTC, natalishulgina commented on Practice/ShulginaN/pep8task.py
> +# неправильный уровень вложенности
С помощью команды reformat code я поняла, что в этих двух блоках (начало в 17 и 31 стр.) уровень вложенности некорректен. Но определить конкретные строки самостоятельно, не получается. Пересмотрю лекцию и попробую разобраться снова. Пока прикрепила задания к 3й лекции. Спасибо!

2022-09-10 09:08 UTC, IlyaOrlov requested changes
Всё супер! Новых замечаний нет. Надо только поправить комментарии к pep8task.py

2022-09-10 09:08 UTC, IlyaOrlov commented on Practice/ShulginaN/pep8task.py
> +# неправильный уровень вложенности
На самом деле сейчас достаточно написать, что некорректны уровни вложенности кода внутри функций. Для большей детализации ответа нужно иметь представление о функциях, циклах и условиях, а мы это еще только будем это проходить)

2022-09-10 10:22 UTC, natalishulgina commented on Practice/ShulginaN/pep8task.py
> +# неправильный уровень вложенности
Спасибо! Внесла изменения.

2022-09-10 12:03 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-10 12:03 UTC, merged