Ibryanova branch
IlyaOrlov/PythonCourse2.0_August22 pull request #33
Opened 2022-09-10 04:20 UTC by Ibryanova

2022-09-10 08:58 UTC, IlyaOrlov requested changes
Добавил замечания к новому коду. Также остаются актуальными замечания из старого Pull Request: https://github.com/IlyaOrlov/PythonCourse2.0_August22/pull/30
1. Не очень понятно, зачем нужна еще одна папка VA_ibryanova, если Вы уже сделали папку Ibryanova.
2. Файлы Home_task_1.py и test_new.py вроде как об оном и том же. Это эксперименты с гит?
3. Папка .idea - это локальные файлы PyCharm. Ее не нужно коммитить.

2022-09-10 08:58 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +          mp3s = [] # не определенна переменная
Какая переменная не определена?

2022-09-10 08:58 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
Согласно PEP8 определение функции должно отделяться от остального кода **двумя** пустыми строками.

2022-09-10 08:58 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_new_2.py
> +result = int(diff) / int(distance)
Зачем здесь делать int(diff)? Ведь diff строкой выше вычисляется как разность двух целых чисел, а значит, это по определению целое число.

2022-09-10 11:15 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +          mp3s = [] # не определенна переменная
mp3s = [] - -эта

2022-09-10 11:20 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
принято

2022-09-10 11:27 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_new_2.py
> +result = int(diff) / int(distance)
исправила

2022-09-10 11:37 UTC, Ibryanova commented
> Добавил замечания к новому коду. Также остаются актуальными замечания из старого Pull Request: #30
> 
> 1. Не очень понятно, зачем нужна еще одна папка VA_ibryanova, если Вы уже сделали папку Ibryanova.
> 2. Файлы Home_task_1.py и test_new.py вроде как об оном и том же. Это эксперименты с гит?
> 3. Папка .idea - это локальные файлы PyCharm. Ее не нужно коммитить.

Отвечаю:
1 . мне так удобно, но могу удалить, если необходимо
2. это был эксперимент с гит, удалить нужно?
3. Папку .idea  я удаляла, но опять появилась

2022-09-10 17:48 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +          mp3s = [] # не определенна переменная
Она-то как раз здесь и определяется. Все последующие проблемы обусловлены некорректными отступами относительно этого определения: интерпретатор просто не может понять, какие границы области видимости у переменной mp3s.
Конкретно в этой строке ошибка заключается в неверном количестве отступов. Так что комментарий стоит поправить.

2022-09-10 17:49 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
Хорошо. Надо еще по пустой строке добавить перед стр.3 и после стр.4

2022-09-10 17:54 UTC, IlyaOrlov requested changes
Еще пару исправлений стоит внести. 
По общим замечаниям:
> 1 . мне так удобно, но могу удалить, если необходимо

Если так удобно - то ОК. Можете оставить. Просто были сомнения, что так непреднамеренно получилось)
> 2. это был эксперимент с гит, удалить нужно?

Можно оставить. Просто уточнил)
> 3. Папку .idea я удаляла, но опять появилась

Да, сейчас она из Pull Request удалилась.  Всё ОК.

2022-09-10 19:40 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
добавила

2022-09-10 19:41 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +          mp3s = [] # не определенна переменная
комментарий поправила

2022-09-11 07:16 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
До того, как Вы добавили пустую строку перед стр.3, на 4-й строке было выражение ```return math.pi * r ** 2```. Именно после него и требовалось добавить ещё одну пустую строку. А в теле функции пустая строка лишняя.

2022-09-11 07:21 UTC, IlyaOrlov requested changes
Хорошо. Но некоторые замечания ещё остались.

2022-09-11 07:21 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +# первым должен быть import os затем  import sys
Кстати, почему? Если располагать их в алфавитном порядке, то тут есть еще претенденты на первые места в списке (argparse, ast).

2022-09-11 07:21 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname)) # лишняя скобка
Учитывая, что количество открывающих скобок должно соответствовать количеству закрывающих, лишних скобок здесь две.

2022-09-11 07:21 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +    # elif переменная не на своем месте, вероятно относится к if args.output:
Нет. Здесь всё правильно. Этот оператор elif относится к  if args.subcommand == 'rename':

2022-09-11 19:35 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/lec_2 task_1.py
> +
поправила

2022-09-11 19:46 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +# первым должен быть import os затем  import sys
в лекции написан был порядок, я думала так и должно быть, коммент убрала

2022-09-11 19:46 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +            os.rename(path + '/' + mp3), path + '/' + hashname)) # лишняя скобка
поправила коммент

2022-09-11 19:46 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +    # elif переменная не на своем месте, вероятно относится к if args.output:
убрала коммент

2022-09-12 05:07 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/pep8task.py
> +# первым должен быть import os затем  import sys
Хорошее наблюдение) Да, обычно импорты в пределах одной группы (например, импорты стандартной библиотеки) сортируют в алфавитном порядке, чтоб было удобней в них ориентироваться. Но это не является требованием.

2022-09-12 05:08 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-12 05:08 UTC, merged