Pep8
IlyaOrlov/PythonCourse2.0_August22 pull request #35
Opened 2022-09-11 12:32 UTC by KseniaKatrashova

Pep8

2022-09-11 17:34 UTC, IlyaOrlov requested changes
Всё ОК. Замечание только по одному комментарию.

2022-09-11 17:34 UTC, IlyaOrlov commented on Practice/Katrashova/les2pep8.py
> +        mp3s = []  # 4 пробела
В смысле 4 пробела лишних или 4 пробела не хватает?)
На самом деле, с этой строкой всё в порядке, а вот код ниже (до стр.40) действительно стоит сдвинуть на 4 пробела вправо, т.к. это всё относится к функции **def restore(...)**.

2022-09-12 19:37 UTC, IlyaOrlov requested changes
Не надо исправлять код в этом файле, только писать комментарии, где допущены ошибки! Иначе появляются новые ошибки)

2022-09-12 19:37 UTC, IlyaOrlov commented on Practice/Katrashova/les2pep8.py
> +    for path, mp3 in mp3s:  # поставила 4 пробела
А здесь они зачем?

2022-09-13 13:46 UTC, IlyaOrlov reviewed
Новых замечаний нет. Ещё уточню на всякий случай про "не надо исправлять код в этом файле". 
Имелось в виду: не надо исправлять первоначальный код в этом задании, чтоб было видно, к чему относятся Ваши комментарии об ошибках.
Если это понятно - ответьте, пожалуйста, и я утвержу изменения. Исправлять ничего не нужно.

2022-09-13 13:56 UTC, Natalia-Grudkova commented
Да, всё понятно.
--
Отправлено из Mail.ru для Android вторник, 13 сентября 2022г., 16:46 +03:00 от IlyaOrlov  ***@***.*** :

***@***.*** commented on this pull request.
>Новых замечаний нет. Ещё уточню на всякий случай про "не надо исправлять код в этом файле".
>Имелось в виду: не надо исправлять первоначальный код в этом задании, чтоб было видно, к чему относятся Ваши комментарии об ошибках.
>Если это понятно - ответьте, пожалуйста, и я утвержу изменения. Исправлять ничего не нужно.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  . 0_August22/pull/35/review/1105837167 @ github . com>

2022-09-13 15:25 UTC, IlyaOrlov approved these changes
Отлично!

2022-09-13 15:26 UTC, merged