Alla turenko branch
IlyaOrlov/PythonCourse2.0_August22 pull request #37
Opened 2022-09-11 23:20 UTC by Wiwingsy

2022-09-12 05:26 UTC, IlyaOrlov requested changes
Хорошо. Но есть несколько замечаний.

2022-09-12 05:26 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +res = 2 * a + 2 * b
Двойку можно вынести за скобки)

2022-09-12 05:26 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +word = str(input("Enter one word: "))
str здесь лишняя: input и так всегда возвращает результат строкового типа.

2022-09-12 05:26 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +if "A" in word:
Немного нелогично получается. Если в слове не будет "A", то сообщение "There is no letter 'A' in this word" напечатается. Но если не будет "a", то для нее аналогичного сообщения не предусмотрено.

2022-09-12 05:26 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +pal = str(input("Enter one word: "))
Тоже лишняя str.

2022-09-12 05:26 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +if pal[0:] == pal[::-1]:
pal[0:] - это по факту то же, что и просто pal. Ни к чему лишние символы.
А поскольку результат операции == и так будет True или False, строки 45-48 можно значительно упростить до print(pal == pal[::-1]).
Вот только один нюанс: что если палиндром начинается с большой буквы?

2022-09-12 13:46 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +res = 2 * a + 2 * b
Даже стыдно стало) Исправила

2022-09-12 14:21 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +word = str(input("Enter one word: "))
Исправила

2022-09-12 14:21 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +if "A" in word:
Исправила

2022-09-12 14:21 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +pal = str(input("Enter one word: "))
Убрала

2022-09-12 14:21 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +if pal[0:] == pal[::-1]:
Исправила

2022-09-12 20:03 UTC, IlyaOrlov requested changes
Почти всё идеально, только один важный нюанс остался!

2022-09-12 20:07 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +if "a" or "A" in word:
Интерпретатор рассматривает данное выражение как ```if ("a") or ("A" in word):```
Поскольку "a" в логическом выражении однозначно преобразуется к True, то и всё выражение будет True независимо от наличия "A" в word.
На самом деле исходный вариант был правильным, только было бы логично, если б у ```if "a" in word:``` был тоже был свой else.

2022-09-14 09:26 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +if "a" or "A" in word:
Что то я не понимаю как сделать, не получается :(  Если у первого блока есть свой else, то программа пишет, что маленьких "a" нет и дальше не идёт и не проверяет на наличие больших "A".
Пыталась менять вложенность, но не помогает. 
word = input("Enter one word: ")

if "a" in word:
    word2 = word.replace("a","*")
else:
    print("There is no letter 'a' in this word")
if "A" in word:
    word3 = word2.replace("A", "*")
    print(word3)
else:
    print("There is no letter 'A' in this word")

2022-09-14 19:33 UTC, IlyaOrlov commented on Practice/aturenko/Homework3.py
> +if "a" or "A" in word:
Тут проблема в путанице с переменными)
```
if "A" in word:
    word3 = word2.replace("A", "")
```
Вы пытаетесь заменить "A" в word2 (а не в word). Однако word2 материализуется, только если до этого выполнилось условие ```if "a" in word:```.
Пожалуй, это тот случай, когда стоит обойтись одной переменной word.

2022-09-14 19:46 UTC, IlyaOrlov requested changes
Очень хорошо! Но ещё есть некоторые замечания!

2022-09-14 19:46 UTC, IlyaOrlov commented on Practice/aturenko/Homework4.py
> +    if a % 3 == 0:
Получается, если число кратно 15 (и 3-м, и 5-ти), то выведется и Fizz, и Buzz, и FizzBuzz. Многовато всего. Стоит начать с проверки максимально частного случая (15), а потом проверять все остальные, используя elif. Тогда в стр.16 можно будет просто написать else.

2022-09-14 19:46 UTC, IlyaOrlov commented on Practice/aturenko/Homework4.py
> +            continue
Здесь должен быть break, и так мы рискуем никогда не выйти из внешнего цикла. Чтоб всё-таки можно было выйти, надо в стр. 56 вместо True использовать некоторую переменную flag (стоит объявить её чуть раньше, как flag = True). А здесь перед break указать flag = False.

2022-09-14 19:46 UTC, IlyaOrlov commented on Practice/aturenko/Homework4.py
> +    if d == c:
**c** - число, **d** - строка.
Если ```c = 5```, а ```d = "5"``` они не будут равны друг другу. 
По этой же причине в стр.81 type(**d**) никогда не будет равен int. 
Мы можем проверить только, что строка **d** состоит из числовых символов (цифр), и после этого привести **d** к типу int, а затем уже сравнивать с числом **c**.

2022-09-14 19:46 UTC, IlyaOrlov commented on Practice/aturenko/Homework4.py
> +    comp_instr = (instr[random_instr])
Круглые скобки лишние.

2022-09-14 19:46 UTC, IlyaOrlov commented on Practice/aturenko/Homework4.py
> +    elif user_instr != "бумага" or "ножницы" or "камень":
Так всё скопом сравнивать нельзя!
Но можно так: ```elif user_instr not in instr:```
Но, кстати, т.к. ни один из предыдущих elif не сработал, то здесь вообще можно обойтись else.

2022-09-14 20:49 UTC, IlyaOrlov commented on Practice/aturenko/Homework5.py
> +git status
Это здесь лишнее)

2022-09-14 21:23 UTC, Wiwingsy commented on Practice/aturenko/Homework3.py
> +if "a" or "A" in word:
Как всё просто оказывается...даже и мысли не было оставить одну переменную. Спасибо

2022-09-14 21:23 UTC, Wiwingsy commented on Practice/aturenko/Homework4.py
> +    if a % 3 == 0:
Исправила

2022-09-14 21:23 UTC, Wiwingsy commented on Practice/aturenko/Homework4.py
> +            continue
Исправила

2022-09-14 21:24 UTC, Wiwingsy commented on Practice/aturenko/Homework4.py
> +    if d == c:
Исправила

2022-09-14 21:24 UTC, Wiwingsy commented on Practice/aturenko/Homework4.py
> +    comp_instr = (instr[random_instr])
Убрала

2022-09-14 21:24 UTC, Wiwingsy commented on Practice/aturenko/Homework4.py
> +    elif user_instr != "бумага" or "ножницы" or "камень":
Да, уже поняла, спасибо!

2022-09-14 21:24 UTC, Wiwingsy commented on Practice/aturenko/Homework5.py
> +git status
Случайно попало вместо терминала) Убрала

2022-09-15 07:39 UTC, IlyaOrlov approved these changes
ОТЛИЧНО!

2022-09-15 07:39 UTC, merged