Grudkova
IlyaOrlov/PythonCourse2.0_August22 pull request #41
Opened 2022-09-13 10:49 UTC by Natalia-Grudkova

2022-09-13 13:35 UTC, IlyaOrlov requested changes
Есть также несколько общих замечаний:
1. У файлов с кодом должно быть расширение .py (т.е. lec2_3.py)
2. Комментарии в Python пишутся со знака #

2022-09-13 13:36 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec2_3
> +    for root, directories, files in os.walk(dirname):               добавление пустой строки, удаление интервалов
Здесь и в строках 34 и 39 добавлять пустые строки не надо. Т.к. весь этот код расположен внутри класса, а тут немного свои правила.

2022-09-13 13:38 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec2_3
> +        for file in files:                                          выравнивание уровня
Здесь и далее комментарий про "выравнивание уровня" следует уточнить: как нужно выровнять (там, где понятно). Либо можно написать "нарушение уровня вложенности" (там, где непонятно).

2022-09-15 07:45 UTC, IlyaOrlov requested changes
Оставил замечания по стилю. Также обратите внимание на старые замечания.

2022-09-15 07:45 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec3.1.py
> +a = input ("Введите длину прямоугольника: ")
Согласно [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call) не должно быть пробела между именем функции и последующей открывающей скобкой.

2022-09-15 07:45 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec3.2.py
> +t = input ("Время в пути: ")
Согласно [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call) не должно быть пробела между именем функции и последующей открывающей скобкой.

2022-09-15 07:45 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec3.3-1.py
> +print (result)
Согласно [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call) не должно быть пробела между именем функции и последующей открывающей скобкой.

2022-09-15 07:45 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec3.3.py
> +print (result)
Согласно [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Immediately%20before%20the%20open%20parenthesis%20that%20starts%20the%20argument%20list%20of%20a%20function%20call) не должно быть пробела между именем функции и последующей открывающей скобкой.

2022-09-15 21:04 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec3.1.py
> +a = input ("Введите длину прямоугольника: ")
исправила

2022-09-15 21:05 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec3.2.py
> +t = input ("Время в пути: ")
исправила

2022-09-15 21:05 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec3.3-1.py
> +print (result)
исправила

2022-09-15 21:05 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec3.3.py
> +print (result)
исправила

2022-09-16 09:04 UTC, IlyaOrlov requested changes
Почти всё исправлено. Остались старые замечания по lec2_3 (надо комментарии скорректировать) и одно небольшое новое пожелание.

2022-09-16 09:04 UTC, IlyaOrlov commented on Practice/nataligrudkova/lec3.3-1.py
> +result = password
result тут несколько лишний
Можно же просто print(password)

2022-09-16 20:25 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec2_3
> +        for file in files:                                          выравнивание уровня
Исправила

2022-09-16 20:25 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec2_3
> +    for root, directories, files in os.walk(dirname):               добавление пустой строки, удаление интервалов
Исправила

2022-09-16 20:26 UTC, Natalia-Grudkova commented on Practice/nataligrudkova/lec3.3-1.py
> +result = password
Исправила

2022-09-17 14:31 UTC, IlyaOrlov approved these changes
Отлично!

2022-09-17 14:31 UTC, merged