home_lec3
IlyaOrlov/PythonCourse2.0_August22 pull request #44
Opened 2022-09-13 18:39 UTC by Ibryanova

2022-09-13 19:52 UTC, IlyaOrlov requested changes
Хорошо. Есть пара замечаний/рекомендаций.

2022-09-13 19:52 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec3_task3.py
> +code = 29859
Раз уж это всё в одном файле задаётся, то можно написать code = res (или даже просто здесь и ниже использовать res).
Да и k переопределять уже тоже не надо (эта переменная уже задана в стр.2).

2022-09-13 19:52 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec3_task4.py
> +s = s.swapcase()
swapcase не поможет! Мы же не можем знать наверняка... вдруг пользователь уже сразу написал всё в нужном регистре. Также нужно понимать, что, меняя регистр у всего слова, мы затрагиваем и другие буквы, кроме "A" и "a", а это в задании не оговорено и может быть нежелательным.
По-правильному, надо последовательно использовать два replace: для "A" и для "a".
Когда мы пройдем регулярные выражения, Вы узнаете ещё один способ замены - при помощи одной операции.

2022-09-14 07:59 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec3_task3.py
> +code = 29859
поправила

2022-09-14 08:03 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec3_task4.py
> +s = s.swapcase()
поправила, спасибо

2022-09-14 19:22 UTC, IlyaOrlov requested changes
Некоторые решения не согласуются с заданиями.

2022-09-14 19:22 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py
> +list = [1,0,8,1,9]
Список из чисел и пятизначное число - это не одно и то же. Тем более, согласно заданию программа должна считывать это число, т.е. оно должно вводиться через input.

2022-09-14 19:22 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py
> +        print(i)
Многовато пробелов.

2022-09-14 19:22 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task3.py
> +    number = int(input("Input a number: "))
Согласно заданию: "Если пользователь ввел не числовой символ, вывести предупреждение и запросить новый символ." А в текущей редакции, если пользователь введёт нечисловой символ - программа упадёт.

2022-09-14 19:22 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_tasl5.py
> +if guess == number:
Отгадывание должно быть реализовано в цикле!

2022-09-17 14:29 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py
> +    print(n)
Согласно заданию надо выводить не только очередную цифру, но и её порядковый номер.

2022-09-18 10:49 UTC, IlyaOrlov requested changes
Добавил замечание. 
И куда-то часть старых файлов подевалась..

2022-09-18 10:49 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py
> +for n in range(0, 6):
Лучше сделать цикл универсальным: привязывать не к конкретным числам, а к длине num:
```python
for n in range(len(num)):
```
Тогда если num и требования к нему поменяются, нам не придётся менять этот цикл.

2022-09-18 11:26 UTC, Ibryanova commented
Илья, здравствуйте, часть файлов исчезла по моей вине, нечаянно их удалила (задание 3 и 5 по 4 лекции). Запушила все файлы, которые были у меня в папке, поэтому жду, когда все проверите и примите, чтоб я могла добавить их заново. Восстановить их сама не смогла
  
>Воскресенье, 18 сентября 2022, 13:49 +03:00 от IlyaOrlov ***@***.***>:
> 
> 
***@***.*** requested changes on this pull request.
>Добавил замечание.
>И куда-то часть старых файлов подевалась..
>----------------------------------------------------------------------
>In  Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py :
>> @@ -0,0 +1,6 @@
>
>+num = "10819"
>
>+if num.isdecimal():
>
>+    print(f"Число {num}")
>
>+
>
>+for n in range(0, 6):
>
>
>Лучше сделать цикл универсальным: привязывать не к конкретным числам, а к длине num:
>for n in range(len(num)):
>Тогда если num и требования к нему поменяются, нам не придётся менять этот цикл.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <IlyaOrlov/PythonCourse2 . 0_August22/pull/44/review/1111523688 @ github . com> 
 
 
С уважением, Валентина
 

2022-09-21 07:28 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task3.py
> +    number = int(input("Input a number: "))
поправила

2022-09-21 07:28 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec4_tasl5.py
> +if guess == number:
сделала

2022-09-21 07:28 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec4_task2.py
> +for n in range(0, 6):
поправила

2022-09-21 08:41 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-09-21 08:41 UTC, merged