Esafonova
IlyaOrlov/PythonCourse2.0_August22 pull request #45
Opened 2022-09-13 20:06 UTC by SafonovaEkaterina

add all files lec.4

2022-09-13 20:31 UTC, IlyaOrlov requested changes
Супер! Но есть несколько замечаний.

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.3.py
> +        continue
continue здесь лишний, т.к. нижеследующий код лежит в ветке else и всё равно не будет выполняться, раз уж мы попали в ветку if.

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.3.py
> +    if n == "stop" or n == "Stop" or n == "STOP":
Можно попроще: if n.lower() == "stop"

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        continue
Здесь и в стр. 15 continue лишний

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Между count и индексом lis явно наблюдается логическая связь lis[count - 1]. Если использовать это наблюдение, то можно убрать лишние условия (кроме if count > len(lis):) и сделать код независимым от количества элементов в списке lis. Это позволит при необходимости добавлять ещё варианты ответов, не меняя основной алгоритм.

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.5.py
> +    if int(answer) == number:
Чтоб не повторять int(answer) несколько раз, можно сначала написать answer = int(answer) и дальше работать просто с answer. Не будем лишний раз вызывать функцию int - сэкономим время выполнения кода.

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.6.py
> +def fun(a, b):
А если a и b равны, что вернётся?

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.8.py
> +        print("Ничья!")
Здесь и в строках ниже многовато пробелов.

2022-09-13 20:31 UTC, IlyaOrlov commented on Practice/esafonova/task4.8.py
> +player = int(input("Введите ваш выбор в числовом варианте: 1 - камень, 2 - ножницы, 3 - бумага.\n Ваш выбор:  "))
Кстати, это очень хорошая идея - сравнивать не строки, а числа. Т.к. процессор выполняется операцию сравнения для чисел в разы быстрее, чем для строк!

2022-09-14 19:39 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.3.py
> +        continue
+

2022-09-14 19:39 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.3.py
> +    if n == "stop" or n == "Stop" or n == "STOP":
+

2022-09-14 19:39 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        continue
+

2022-09-14 19:40 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Исправила. При count = 4 не выводится print. Не могу отловить.

2022-09-14 19:40 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.5.py
> +    if int(answer) == number:
+

2022-09-14 19:40 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.6.py
> +def fun(a, b):
+

2022-09-14 19:40 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.8.py
> +        print("Ничья!")
+

2022-09-14 19:42 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.8.py
> +player = int(input("Введите ваш выбор в числовом варианте: 1 - камень, 2 - ножницы, 3 - бумага.\n Ваш выбор:  "))
+
Использовала, как шаблон, решение, которое уже готовила ранее на JS.

2022-09-14 20:46 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Потому что в этом случае НЕ выполняется ветка else (где этот print находится). 
else вообще стоит убрать, а count лучше начинать с 1, не с 0.

2022-09-14 20:54 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
В новом файле я имею в виду. 

lis = ["Ты сам-то понял, что написал?", "Аргументируй", "И?"]
count = 0

while True:
    n = input("Ваш запрос: ")
    count += 1
    if count > len(lis):
        count = 0
    elif n == "хватит":
        break
    else:
        print(lis[count - 1])
        continue

Вывод:
Ваш запрос: 1
Ты сам-то понял, что написал?
Ваш запрос: 2
Аргументируй
Ваш запрос: 3
И?
Ваш запрос: 4 #пропуск ответа на запрос
Ваш запрос: 5
Ты сам-то понял, что написал?
Ваш запрос:

2022-09-14 20:58 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Ну так... 
При count == 4 срабатывает условие 
```
if count > len(lis):
    count = 0
```
поэтому до ветки
```
else:
    print(lis[count - 1])
```
интерпретатор вообще не доходит и сразу переходит к n = input("Ваш запрос: ").

2022-09-14 21:05 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Я поняла как реализовать задачу по-другому, но мне все таки важно решить это со счетчиком. 

n = ""
lis = ["Ты сам-то понял, что написал?", "Аргументируй", "И?"]
while True:
    for i in lis:
        if n == "хватит":
            continue
        else:
            n = input("Ваш запрос: ")
            print(i)

2022-09-14 21:10 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
```python
lis = ["Ты сам-то понял, что написал?", "Аргументируй", "И?"]
count = 0

while True:
    n = input("Ваш запрос: ")
    count += 1
    if count > len(lis):
        count = 1
    elif n == "хватит":
        break
    print(lis[count - 1])
```

2022-09-14 21:13 UTC, IlyaOrlov commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
> Я поняла как реализовать задачу по-другому, но мне все таки важно решить это со счетчиком.
> 
> n = "" lis = ["Ты сам-то понял, что написал?", "Аргументируй", "И?"] while True: for i in lis: if n == "хватит": continue else: n = input("Ваш запрос: ") print(i)

А это решение, кстати, приводит к бесконечному циклу!

2022-09-14 21:14 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Очевидно же. Спасибо большое. Видимо замылилось уже )))

2022-09-14 21:16 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-14 21:16 UTC, merged

2022-09-14 21:16 UTC, SafonovaEkaterina commented on Practice/esafonova/task4.4.py
> +        print(lis[1])
Все исправила. Еще раз большое спасибо.