Kharin b
IlyaOrlov/PythonCourse2.0_August22 pull request #47
Opened 2022-09-13 20:43 UTC by Tetrackon

2022-09-14 12:37 UTC, IlyaOrlov requested changes
Всё классно! В Task8.py вообще очень оригинальное решение)
Оставил только пару вопросов.

2022-09-14 12:37 UTC, IlyaOrlov commented on Practice/KharinB/Task5.py
> +                range_min = int(range_min)
Лучше сначала привести их к int, а потом выполнять все проверки (числа сравниваются быстрее строк). К тому же код здесь и в стр.17 почти одинаковый.
И что если range_max == range_min?

2022-09-14 12:37 UTC, IlyaOrlov commented on Practice/KharinB/Task5.py
> +        elif answer > range_max or answer < range_min:
А что если answer == range_max или вообще num == range_min?

2022-09-14 20:34 UTC, IlyaOrlov commented on Practice/KharinB/Task5.py
> +                # В пайтоне есть библиотека math, в которой есть функция abs(), которая возвращает модуль числа.
Да, тащить библиотеку ради одного решение излишне. Но что если сначала сравнить range_max, range_min на больше/меньше, а потом уже проверять явно положительную разность range_max - range_min.

2022-09-14 20:37 UTC, IlyaOrlov reviewed
Ответил по возведению в степень. Других замечаний/вопросов нет.

2022-09-15 07:32 UTC, Tetrackon commented on Practice/KharinB/Task5.py
> +                # В пайтоне есть библиотека math, в которой есть функция abs(), которая возвращает модуль числа.
Добрый день! Мне показалось что это не совсем логично со стороны пользователя - сначала заставить его поменять местами числа, а потом сообщить что диапазон слишком мал, и повторно заставить вводить всё сначала. В таком решении как у меня, код стал на пару символов длиннее, но зато мы не требуем от пользователя лишних решений, которые потом обнулятся. Отсюда вопрос -  с какой стороны подходить к решению таких вопросов в домашнем задании?

2022-09-15 08:03 UTC, IlyaOrlov commented on Practice/KharinB/Task5.py
> +                # В пайтоне есть библиотека math, в которой есть функция abs(), которая возвращает модуль числа.
Вопрос, на самом деле, серьёзный и глобальный. Довольно часто приходится делать выбор между максимальным удобством пользователя и предотвращением излишнего усложнения кода. В реальной разработке этот выбор делается ответственным за продукт и ответственным за архитектуру (обычно, это разные люди). На нашем курсе оба вида ответственности лежат на самом слушателе:) Я могу только подсветить какие-то существенные ошибки, недочёты, важные вопросы.
В данном случае Ваша аргументация в пользу удобства слушателя весьма убедительна. Серьёзного усложнения данный код не вносит. Поэтому можно оставить и так.

2022-09-15 08:13 UTC, Tetrackon commented on Practice/KharinB/Task5.py
> +                # В пайтоне есть библиотека math, в которой есть функция abs(), которая возвращает модуль числа.
Принял. Мне нужно выложить задание с дополнительными комментариями? Или можно закрывать пулл реквест? Или лучше не закрывать пулл реквест пока не сделаю последнее задание?

2022-09-15 09:35 UTC, IlyaOrlov commented on Practice/KharinB/Task5.py
> +                # В пайтоне есть библиотека math, в которой есть функция abs(), которая возвращает модуль числа.
Можно и так и оставить)

2022-09-15 09:35 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-09-15 09:36 UTC, merged