Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #48
Opened 2022-09-14 08:49 UTC by natalishulgina

некоторые дз к 4 лекции + разделила на папки

2022-09-14 19:26 UTC, IlyaOrlov requested changes
Всего одно замечание)

2022-09-14 19:26 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_4/task2.py
> +    print(n)
Надо ещё индекс выводить: завести некоторую переменную (например, count = 1), выводить её вместе с n, увеличивать на единицу (count += 1) на каждой итерации цикла... и всё получится)

2022-09-14 22:23 UTC, natalishulgina commented on Practice/ShulginaN/Lec_4/task2.py
> +    print(n)
Невнимательно прочитала задание) спасибо, поправила.

2022-09-15 07:34 UTC, IlyaOrlov requested changes
Всё хорошо! Есть пара комментариев/предложений по оптимизации.

2022-09-15 07:34 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_4/task3.py
> +        continue
continue здесь не нужно: весь последующий код лежит в else - он и так не выполнится, раз уж мы зашли в elif.

2022-09-15 07:34 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_4/task5.py
> +    elif int(c) > number:
Можно ли как-то сделать приведение к числовому типу (int(c)) однократным? Чтоб не повторять эту операцию в стр.13 и стр.15

2022-09-15 11:39 UTC, natalishulgina commented on Practice/ShulginaN/Lec_4/task3.py
> +        continue
ок, понятно.

2022-09-15 11:40 UTC, natalishulgina commented on Practice/ShulginaN/Lec_4/task5.py
> +    elif int(c) > number:
Да, можно добавить доп. строку c = int(c). По-другому не знаю как(

2022-09-15 21:43 UTC, natalishulgina commented on Practice/ShulginaN/Lec_4/task5.py
> +    elif int(c) > number:
Скорректировала task 5, 3 и добавила новые файлы 6 и 8. Жду обратной связи)

2022-09-16 09:23 UTC, IlyaOrlov approved these changes
Всё отлично! Замечаний нет.

2022-09-16 09:23 UTC, merged