Ogarbis
IlyaOrlov/PythonCourse2.0_August22 pull request #51
Opened 2022-09-14 17:18 UTC by Chipmunk77

Добрый вечер! Задания 1,2,3,4,5 и 8 к лекции №4

2022-09-14 20:28 UTC, IlyaOrlov requested changes
Хорошо, но есть некоторые замечания.

2022-09-14 20:28 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t1.py
> +    if x % 3 == 0 and x % 5 == 0:
Можно чуть проще: if x % 15 == 0

2022-09-14 20:28 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t3.py
> +    if x == "STOP" or "Stop" or "stop":
Интерпретатор воспринимает это как if (x == "STOP") or ("Stop") or ("stop"):
Т.к. непустая строка ("Stop" или "stop") в логическом выражении воспринимается, как True, то и всё выражение всегда будет True независимо от реального значения x.
Лучше так: ```if x in ("STOP", "Stop", "stop")``` или так: ```if x.lower() == "stop"```.

2022-09-14 20:28 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t4.py
> +#помогите, пжл, понять в чем ошибка: при вводе "хватит" на печать выводится ответ (из answers) и "До свидания!". Но ответ выводится не должен. Цикл должен завершаться
В стр.11 пользователь вводит "хватит", потом в стр. 13 выводится answer, затем по циклу в стр.8-9 идёт проверка и выход из цикла. 
Чтоб избежать непреднамеренного вывода answer, надо сначала запрашивать request, потом сравнивать с "хватит" и только после этого выбирать и выводить answer.
Т.е порядок инструкций в теле цикла надо пересмотреть.

2022-09-14 20:28 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t5.py
> +    guess = int(input("Введите целое число из заданного диапазона: "))
Если пользователь введёт не число, то программа упадёт с ошибкой(

2022-09-14 20:28 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t8.py
> +computer_action = random.choice(actions)
Этот выбор компьютера нигде не используется, т.к. сразу после (в стр. 9) он делает новый выбор.

2022-09-16 08:05 UTC, IlyaOrlov requested changes
Всё замечательно! Оставил небольшой комментарий/пожелание.

2022-09-16 08:05 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t8.py
> +gamer_action = " "
Эта инициализация gamer_action нигде не используется, т.к. сразу после (в стр.7) gamer_action переопределяется.
Ну и еще было бы неплохо дать пользователю возможность выйти из игры:) Например, если он введёт stop.

2022-09-17 14:27 UTC, IlyaOrlov requested changes
Остался один вопрос.

2022-09-17 14:27 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t6.py
> +        print("Числа равны")
Вопрос на понимание: что возвращает find_max в этом случае? Чему будет равна переменная res, если a и b равны?

2022-09-17 16:49 UTC, Chipmunk77 commented on Practice/GarbisO/lec4 t6.py
> +        print("Числа равны")
С пониманием пока сложно....) предположу, что если после else нет условия возврата (return), то при равных значениях функция вернет None. А res будет равен значению первого фактического аргумента (не уверена)

2022-09-18 10:36 UTC, IlyaOrlov commented on Practice/GarbisO/lec4 t6.py
> +        print("Числа равны")
Верно на 50%
Отсутствие return в ветке else равносильно return None.
Этот None и подставится по месту вызова функции (в стр.13). Получится res = None.
Если это приемлемое поведение функции (т.е. Вы так и хотели, чтоб в случае равенства возвращался None), имеет смысл явно прописать return None после стр.8. Иначе это будет выглядеть, как будто автор кода забыл про возврат значения в случае равенства a и b.

2022-09-18 14:16 UTC, Chipmunk77 commented on Practice/GarbisO/lec4 t6.py
> +        print("Числа равны")
Спасибо, стало понятнее!

2022-09-18 16:33 UTC, Chipmunk77 commented
Добрый вечер! Задание с декоратором. Сделала только благодаря шаблону с лекции... Как и с рекурсией вроде интуитивно понятно, что это и зачем применяется. Но понять механизм работы, а тем более самостоятельно написать пока не выходит

2022-09-18 20:07 UTC, IlyaOrlov requested changes
Всё ОК. Надо только код в decorator.py покрасивей оформить.

2022-09-18 20:07 UTC, IlyaOrlov commented on Practice/GarbisO/decorator.py
> +#вариант №1
По коду всё ОК, только надо немного красоту навести:
1. После определения функции (стр.12-13) не помешает пара пустых строк.
2. Чтоб оба способа лучше уживались в одном файле, декоратор 2-й раз переписывать не нужно (стр.18-25), а функцию из 2-го примера (стр.29) можно назвать по-другому (например, mysum1).

2022-09-19 07:59 UTC, Chipmunk77 commented on Practice/GarbisO/decorator.py
> +#вариант №1
Добрый день!
Спасибо, исправила (поменяла на другую функцию в стр.29)

2022-09-19 19:07 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-09-19 19:07 UTC, merged