Задания 5 лекции. 1 и 2
IlyaOrlov/PythonCourse2.0_August22 pull request #52
Opened 2022-09-15 21:29 UTC by Kuduzo

2022-09-16 09:19 UTC, IlyaOrlov requested changes
Всё хорошо! Добавил предложение по оптимизации и информацию к размышлению.

2022-09-16 09:19 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 05/Task01.py
> +    arr[i], arr[i+min_index] = arr[i+min_index], arr[i]
Отличное решение! Использование своей функции, позволяющей находить индекс минимального элемента - это эффективнее, чем комбинация из стандартных min и index методов Python.
Только ещё стоит добавить проверку, чтоб не переставлять элементы, когда i == min_index.

2022-09-16 09:19 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 05/Task02.py
> +arr = list(sorted(enumerate(old_arr), key=lambda x: x[1]))  # O(n*log(n)) > O(n) => O(n*log(n))
Сортировать список ради поиска **только первого повторившегося** элемента - это лишняя работа. Можно добиться алгоритмической сложности O(n). 
Для этого нужно просто идти по списку, сохранять просмотренные элементы в отдельный контейнер, предварительно проверяя, нет ли уже очередного элемента в этом контейнере.
Правда, тут нужен такой вспомогательный контейнер, чтоб сложность поиска в нём составляла О(1).   Список не подойдёт.

2022-09-19 19:42 UTC, IlyaOrlov requested changes
Можно сделать ещё одно существенное улучшение.

2022-09-19 19:42 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 05/Task02.py
> +for i in range(len(old_arr)):  # O(n)
Учитывая, что обращение по индексу в списке - не такая уж быстрая операция, да и сам индекс в этом алгоритме нам не нужен, имеет смысл идти сразу по элементам, а не по индексам.

2022-09-19 21:23 UTC, Kuduzo commented
Да, действительно. Почему-то не обратил в этот раз, что индекс не используется, и достаточно всего лишь перебирать элементы, что влияет как минимум на читаемость и упрощает понимание. Но в целом скорость работы в цикле через индекс и через элементы одинаковая - O(n).

2022-09-20 07:18 UTC, IlyaOrlov approved these changes
Теперь всё отлично!
Да, относительная сложность в любом случае будет O(n)

2022-09-20 07:18 UTC, merged