Katrashova branch
IlyaOrlov/PythonCourse2.0_August22 pull request #54
Opened 2022-09-17 17:43 UTC by KseniaKatrashova

не понимаю что не так

2022-09-18 10:44 UTC, IlyaOrlov requested changes
В задании les4.1.py надо цикл использовать!
А старые файлы Вы совсем удалить решили, или по подпапкам хотите разместить. Пока всё выглядит, как первый вариант.

2022-09-18 10:44 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.1.py
> +a = randint (1, 100)
ОК. Только нужно не одно случайное число из диапазона 1 - 100 брать, а пройтись по всему диапазону и каждое число проверить. В этом поможет, например, цикл while.
Проверку каждого числа стоит всё-таки начинать с a % 15, иначе всё что кратно 15 (а значит и кратно 3) будет уходить в ветку:
```python
if a % 3 == 0:
    print("Fizz")
```
и до следующих проверок дело даже не дойдёт.

2022-09-18 20:01 UTC, IlyaOrlov requested changes
Стало лучше, но ещё есть, что поправить.

2022-09-18 20:01 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.1.py
> +from random import random, randint
Эта строка стала лишней.

2022-09-18 20:01 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.1.py
> +        continue
continue лишний: после стр.13 (последней в теле цикла) интерпретатор и так перейдет на следующую итерацию цикла.

2022-09-18 20:01 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.1.py
> +while a<=99:
Будет всё-таки читабельней и понятней, если мы начнём с ```a = 1```, в условии напишем ```a <= 100```, а ```a += 1``` напишем в конце тела цикла (только не внутри if-elif-else).

2022-09-19 06:17 UTC, KseniaKatrashova commented on Practice/Katrashova/lesson4/les4.1.py
> +while a<=99:
как мне с остальных лекций закинуть все сюда?

2022-09-19 19:10 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.1.py
> +while a<=99:
Через commit и push...
Видимо, получилось закинуть)

2022-09-19 19:13 UTC, IlyaOrlov requested changes
Добавил несколько замечаний.

2022-09-19 19:13 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.2.py
> +while i in range(len[a]):
Это гибрид из двух циклов получился:)
1. in работает только с for
2. len - это функция, параметры передаются в функцию в круглых скобках: len(a)

2022-09-19 19:13 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.2.py
> +    print("{i} цифра равна (a{i})")
обращение к i-му элементу должно выполняться так: a[i]

2022-09-19 19:13 UTC, IlyaOrlov commented on Practice/Katrashova/lesson4/les4.2.py
> +    i = i+1
Лучше: i += 1

2022-09-22 16:36 UTC, IlyaOrlov approved these changes
Теперь отлично!

2022-09-22 16:36 UTC, merged