Alla turenko branch
IlyaOrlov/PythonCourse2.0_August22 pull request #57
Opened 2022-09-19 13:20 UTC by Wiwingsy

Здравствуйте, Илья! Не сделала вторую задачу из Лекции №6 про поиск повторяющегося элемента в списке. В комментариях к своей попытке решения написала, что именно не понимаю как сделать...Может быть подскажете? Устала уже над этим сидеть. Подсмотрела у других - не очень поняла(Богдан, Сергей).

2022-09-19 19:32 UTC, IlyaOrlov requested changes
Оставил несколько замечаний.

2022-09-19 19:32 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +        print("===========")
Не хватает возврата res из этой подменной функции.
Иначе после применения декоратора нельзя будет сделать, например, так: 2 * mysum(10, 20)

2022-09-19 19:32 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +    def wrapper(x, y):
Стоит сделать подменную функцию универсальной по аргументам.

2022-09-19 19:32 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +    newarr.append(min(arr))
Оригинально) Пожалуй, это решение тоже можно оставить. Но стоит ещё подумать, как решить эту же задачу, не используя дополнительных списков (и вообще дополнительных контейнеров).

2022-09-19 19:32 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +for element in input("Введите числа через пробел: ").split():
Надеюсь, после разбора задачи на лекции, её решение уже не будет представлять особой сложности.

2022-09-19 19:32 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +            for a[i] in a[i+1:len(a):]: # хочется найти а[i] в срезе типа дальше него самого по порядку..
Мысль логичная, только формулировка задания предполагает поиск элемента среди просмотренных.

2022-10-04 13:42 UTC, Wiwingsy commented
Здравствуйте! Учла замечания, доделала все оставшиеся задачи к лекции. Посмотрите пожалуйста...

2022-10-06 07:30 UTC, IlyaOrlov requested changes
Всё хорошо. Добавил несколько предложений по оптимизации.

2022-10-06 07:30 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +        if arr[i] in arr[:i:]:
arr[:i:] - срез - это фактически новый список. Искать в нем элементы через in долго. Есть более подходящий контейнер, куда можно складывать просмотренные элементы.

2022-10-06 07:30 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +                [row.pop(i) for row in anylist]
Так у нас из удаляемых элементов формируется список, который никому не нужен. Только память занимает. Лучше просто написать цикл (хоть и получится две строки, а не одна).

2022-10-06 07:30 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +def wspace(filename):
Функции tab и wspace очень похожи. Нельзя ли вместо двух написать одну универсальную функцию.
Кстати, символ табуляции - это всё-таки \t. А чтоб его было видно при выводе на экран можно сделать так: print(repr(mystring))

2022-10-25 13:24 UTC, Wiwingsy commented on Practice/aturenko/Homework6.py
> +        if arr[i] in arr[:i:]:
Я так поняла вы про множество. Исправила

2022-10-25 13:24 UTC, Wiwingsy commented on Practice/aturenko/Homework6.py
> +                [row.pop(i) for row in anylist]
Исправила

2022-10-25 13:24 UTC, Wiwingsy commented on Practice/aturenko/Homework6.py
> +def wspace(filename):
Исправила

2022-10-25 17:21 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +        if arr[i] in arr[:i:]:
Да, речь о множестве. Но теперь другая ошибка появилась.
В s мы складываем i. А проверяем arr[i] in s.
arr[i] здесь вообще не нужно использовать, т.к. i - не индекс элемента списка, а сам элемент.
Ну и сначала надо выполнить проверку  i in s, а потом уже складывать i в s.

2022-10-25 17:25 UTC, IlyaOrlov requested changes
Все хорошо. Только одно новое замечание надо исправить.

2022-10-25 21:21 UTC, Wiwingsy commented on Practice/aturenko/Homework6.py
> +        if arr[i] in arr[:i:]:
мм... вроде бы исправила, спасибо! Возможно опять не правильно конечно))

2022-10-26 07:24 UTC, IlyaOrlov approved these changes
Теперь правильно. Отлично!

2022-10-26 07:24 UTC, IlyaOrlov commented on Practice/aturenko/Homework6.py
> +        if arr[i] in arr[:i:]:
Теперь правильно_

2022-10-26 07:24 UTC, merged