Esafonova
IlyaOrlov/PythonCourse2.0_August22 pull request #58
Opened 2022-09-19 13:57 UTC by SafonovaEkaterina

add 5.1

2022-09-19 19:37 UTC, IlyaOrlov requested changes
Всё ОК. Но есть пара вопросов/комментариев.

2022-09-19 19:37 UTC, IlyaOrlov commented on Practice/esafonova/task5.1.py
> +        arr[m], arr[i] = arr[i], arr[m]
Стоит повесить проверку if m != i на эту перестановку, чтоб лишний раз её не делать)

2022-09-19 19:37 UTC, IlyaOrlov commented on Practice/esafonova/task5.2.py
> +    for i in range(len(arr)):
ОК. Хотя с использованием set было бы эффективней.
Вопрос на понимание: что вернёт функция, если в списке нет повторений?

2022-09-20 08:48 UTC, SafonovaEkaterina commented on Practice/esafonova/task5.2.py
> +    for i in range(len(arr)):
None

2022-09-20 08:48 UTC, SafonovaEkaterina commented on Practice/esafonova/task5.1.py
> +        arr[m], arr[i] = arr[i], arr[m]
Добавила)

2022-09-20 21:09 UTC, IlyaOrlov commented on Practice/esafonova/task5.2.py
> +    for i in range(len(arr)):
ОК. Вообще, лучше прописывать в таких случаях return None явно, чтоб показать, что мы не забыли предусмотреть возврат в этом случае и как раз планировали вернуть None.

2022-09-20 21:10 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-09-20 21:10 UTC, merged