Задания 3 4 5 последней лекции
IlyaOrlov/PythonCourse2.0_August22 pull request #61
Opened 2022-09-24 17:56 UTC by Kuduzo

2022-09-25 17:02 UTC, IlyaOrlov requested changes
Существенное замечание по заданию 5.4

2022-09-25 17:02 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 05/Task04.py
> +    column_for_del = int(input("Введите столбец для удаления: "))
Согласно заданию столбцы нужно удалять не по заданным индексам, а по значению, которые эти столбцы содержат. Т.е., если пользователь указал число 5, то нужно удалить все столбцы, содержащие число 5.
Ну и чисто практическая рекомендация: помимо ввода пользователя имеет смысл завести несколько константных матриц с предопределенными данными для тестовых целей (чтоб изменения в коде можно было проверять за один запуск программы без повторного ввода информации).

2022-09-26 19:26 UTC, IlyaOrlov requested changes
Остался ещё нюанс!

2022-09-26 19:26 UTC, IlyaOrlov commented on Practice/RybnikovS/Day 05/Task04.py
> +def find_column_for_del(inner_arr, inner_elem):
В целом, всё хорошо... Но что если один столбец попадёт в new_array дважды? Например, для матрицы 
my_array = [[1, 2, 2], [4, 5, 2], [6, 7, 8]] (удаляем столбцы с 2-кой).
Можно ли это предусмотреть на этапе определения new_array?

2022-09-26 20:05 UTC, Kuduzo commented
Обернул в set для удаления дублей и обратно в list

2022-09-27 20:20 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 05/Task04.py
> +    return list(set(new_array))
Так не проще ли сразу сделать new_array = set() ?

2022-09-30 11:32 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-09-30 11:32 UTC, merged