Rybnikov Sergey Lec 6 Ex 1
IlyaOrlov/PythonCourse2.0_August22 pull request #63
Opened 2022-09-26 20:13 UTC by Kuduzo

Заготовка для игры в танки

2022-09-27 20:31 UTC, IlyaOrlov requested changes
Класс, в целом - ОК. Но есть несколько замечаний.

2022-09-27 20:31 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +    def wrap_action(func):
Стоит сделать этот декоратор статическим методом.

2022-09-27 20:31 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +        dict_health = {"Light" : 300, "Medium" : 600, "Heavy" : 1000}
Константные наборы dict_health, inc_health, dict_speed_damage, inc_damage, константу basic_damage, логически связанные с классом, стоит сделать атрибутами класса, чтоб не тратить время на пересоздание этих объектов при каждом вызове соответствующих методов.

2022-09-27 20:31 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +        return health
Чтоб не писать потом my_tank.current_health = my_tank.health() используйте здесь self:
self.health = dict_health[self.weight] * inc_health[self.fraction]
Тогда достаточно будет вызвать: my_tank.health(), и всё само присвоится, куда нужно.
Только название метода health() и поля health надо сделать отличающимися.

2022-09-27 20:31 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +        return inner_health
Здесь аналогично health(). Используйте self. Он здесь как раз указывает на my_tank.

2022-09-27 20:31 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +        self.fraction = all_fractions[int(input("Press: 0 - Play as Allies, 1 - Play as Soviet: "))]
Как и в случае с функциями, все input лучше делать вне класса. Тогда класс можно проверять в т.ч. и на каких-то предопределенных данных.

2022-09-28 20:02 UTC, Kuduzo commented
Добавил задание 2 и 3

2022-09-29 13:00 UTC, IlyaOrlov requested changes
Осталось замечание по Танку.
С заданиями по Лекции5, как я понимаю, мы разбираемся в другом PullRequest.

2022-09-29 13:00 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 06/Task01.py
> +    dict_health = {"Light": 300, "Medium": 600, "Heavy": 1000}
Хотя четкого указания на порядок расположения полей и методов в классе в PEP8 нет, лучше поля класса писать вверху (сразу после имени), а потом уже перечислять методы (я не встречал, чтоб в каком-то проекте отступали от этого порядка). 
Кстати,
        all_fractions = ("Allies", "Soviet")
        all_weights = ("Light", "Medium", "Heavy")
стоит тоже сделать атрибутами класса.

2022-09-29 14:36 UTC, Kuduzo commented
Да, задания для лекции 6 решил делать в новом бранче. Задание лекции 5 забыл запушить

2022-09-30 11:36 UTC, IlyaOrlov reviewed
Замечаний нет. Но надо еще сделать git pull из main, чтоб подтянуть сюда свежие изменения из свежезалитого Pull Request https://github.com/IlyaOrlov/PythonCourse2.0_August22/pull/61
Иначе эти файлы из Lec 05 перетрут в main последние исправления.

2022-09-30 12:06 UTC, Kuduzo commented
готово

2022-09-30 12:17 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-09-30 12:17 UTC, merged