Ogarbis
IlyaOrlov/PythonCourse2.0_August22 pull request #64
Opened 2022-09-27 07:20 UTC by Chipmunk77

Добрый день!
Задания №1, 2, 3 к лекции 5 (Структуры данных)

2022-09-27 20:41 UTC, IlyaOrlov requested changes
Хорошо. Но есть вопросы и небольшие замечания.

2022-09-27 20:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t3.py
> +def replace(s,dict):
dict - зарезервированное слово, не стоит его использовать для обозначения переменных (обычно, PyCharm такое подсказывает).

2022-09-27 20:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t2.py
> +    lst1 = []
Есть более эффективный контейнер для операции in.

2022-09-27 20:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t2.py
> +res = check_symbol(lst)
Чему будет равна res после выполнения функции? И что это даст?

2022-09-27 20:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t1.py
> +        min = i
min - имя стандартной функции, не стоит его использовать для своих переменных.

2022-09-27 20:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t1.py
> +res = fun(arr)
В чем смысл res в данном случае?

2022-10-03 13:52 UTC, Chipmunk77 commented
Добрый день!
Исправленные задания с ответами + новые

2022-10-04 12:38 UTC, IlyaOrlov requested changes
Добавил несколько новых небольших замечаний.

2022-10-04 12:38 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t1.py
> +#смысл Res объяснить не могу, убрала из вызова функции
Заодно убрали и сам вызов функции)
На самом деле, если бы fun что-то возвращала (в ней был бы return), то и смысл в res тоже бы был (переменная для работы с результатом функции). А так, смысла нет. Функция меняет сам arr, который мы передали.

2022-10-04 12:38 UTC, IlyaOrlov commented on Practice/GarbisO/lec6 t2.py
> +    def __lt__(self, other):
Метод должен вернуть имя большей утки, а не вывести на экран.

2022-10-04 12:38 UTC, IlyaOrlov commented on Practice/GarbisO/lec6 t2.py
> +        print(f"Общий вес уток: {self.weight + other.weight}")
Метод должен вернуть суммарный вес уток, а не вывести на экран.

2022-10-04 12:38 UTC, IlyaOrlov commented on Practice/GarbisO/lec6 t2.py
> +Duck1 = Duck("Луи", 1)
Не забываем про именование переменных в snake_case, маленькими буквами.

2022-10-04 12:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t3.py
> +    for key in mydict:
Чтоб потом не обращаться к значению через mydict[key], можно получать его сразу здесь:
for key, value in mydict.items()

2022-10-04 16:25 UTC, Chipmunk77 commented on Practice/GarbisO/lec5 t1.py
> +#смысл Res объяснить не могу, убрала из вызова функции
Вот тепеееерь понятно! Если функция совершает какие-то манипуляции с аргументами и возвращает результат,то нужен res. А если же функция изменяет переданный аргумент и возвращает его в новом виде, то res не нужен
Спасибо!

2022-10-04 16:25 UTC, Chipmunk77 commented
Добрый день!
Исправила замечания + добавила новые задания

2022-10-06 07:48 UTC, IlyaOrlov requested changes
Хорошо. Осталось несколько замечаний, и добавились новые.

2022-10-06 07:48 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t1.py
> +#смысл Res объяснить не могу, убрала из вызова функции
Всё верно. Но сам вызов функции надо вернуть)
fun(arr)
Иначе список не отсортируется.

2022-10-06 07:48 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t3.py
> +        s = s.replace(str(key), str(mydict[key]))
Осталось использовать полученное value по назначению:
s = s.replace(str(key), str(value))

2022-10-06 07:48 UTC, IlyaOrlov commented on Practice/GarbisO/lec6 t3.py
> +        self._filepath = r"C:\Users\Лисичка\PythonCourse2.0_August22\Practice\GarbisO\File_for_task.txt"
Использование абсолютного пути приведёт к тому, что этот скрипт не будет работать на других компьютерах кроме Вашего. Просто потому что у меня нет такой папки "C:\Users\Лисичка\".
Лучше использовать относительный путь (просто "File_for_task.txt") или функцию mktemp(), рекомендуемую в задании.

2022-10-06 07:48 UTC, IlyaOrlov commented on Practice/GarbisO/lec6 t3.py
> +               print(file.read())
Геттер должен возвращать прочитанную строку, а не выводить на экран.

2022-10-07 18:41 UTC, IlyaOrlov commented on Practice/GarbisO/lec5 t3.py
> +        s = s.replace(str(key), str(mydict[key]))
Код до замены работал, но неэффективно. mydict[key] - это целая операция, заставляющая интерпретатор идти по списку и искать элемент с индексом key, чтоб вернуть его значение. А value сразу указывает на значение очередного элемента.

2022-10-07 18:47 UTC, IlyaOrlov requested changes
Остались ещё замечания/пожелания.

2022-10-07 18:47 UTC, IlyaOrlov commented on Practice/GarbisO/lec 7 t1,2.py
> +        print("Новый класс")
Вот только у Pupil уже имени не будет(
Надо задействовать конструктор базового класса!

2022-10-07 18:47 UTC, IlyaOrlov commented on Practice/GarbisO/lec 7 t1,2.py
> +        print("I'm not ready yet")
Здесь лучше просто вызвать метод solve_task базового класса. Смысл в том, что Pupil, выждав время, должен делать ТО ЖЕ, что и его родительский класс - Man. Если мы что-то поменяем в поведении родительского класса (например, будем выводить "I'm ready"), то дочерние классы автоматически подхватят это изменение.

2022-10-10 19:35 UTC, IlyaOrlov requested changes
ОК. Осталось исправить [замечание по уткам](https://github.com/IlyaOrlov/PythonCourse2.0_August22/pull/64/files/9c0795ae4ee2d7884d9f2ff68733d72168c623ba#r986811095).

2022-10-12 09:39 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-12 09:40 UTC, merged