Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #66
Opened 2022-09-28 20:50 UTC by natalishulgina

Сложно решать дз, без практики и когда каша в голове:( что-то укладывается и понимаю сама, что то подсказывают. Столкнулась с проблемой в 4 задании. Дадите подсказку?

2022-09-29 13:10 UTC, IlyaOrlov requested changes
Хорошо. Добавил несколько замечаний.
д/з и есть практика:)

2022-09-29 13:10 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_1.py
> +        if arr[i] > arr[m]:
Это сортировка пузырьковым методом. В задании требуется реализовать сортировку методом выбора (и даже шаги алгоритма расписаны).

2022-09-29 13:10 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_2.py
> +        if a[i] in a[:i:]:
Искать элемент в списке (пусть даже в срезе) долго. Лучше складывать просмотренные элементы в set и искать повторы там.

2022-09-29 13:10 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_3.py
> +for i in d:
Чтоб потом не обращаться к значению через d[i], можно получать его сразу здесь:
for i, value in d.items()

2022-09-29 13:10 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_4.py
> +        for m in range(len(ls)):
Здесь нам нужна длина не внешнего списка len(ls), а очередной строки - len(ls[i]).

2022-09-29 13:10 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_5.py
> +if my_choice == "1":
В блоках if и elif много одинакового кода. Не стоит ли общие части вынести из тела условного оператора?

2022-10-03 18:19 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_3.py
> +for i in d:
Спасибо, правки внесла)

2022-10-03 18:19 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_2.py
> +        if a[i] in a[:i:]:
Ок, спасибо скорректировала.

2022-10-03 18:36 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_4.py
> +        for m in range(len(ls)):
Точно! Поправила, благодарю!

2022-10-03 18:54 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_5.py
> +if my_choice == "1":
Добавила менеджер контекста. Илья, напомните пожалуйста, как проверить закрылся ли файл после цикла?

2022-10-04 12:44 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_4.py
> +        for m in range((len(ls[i]))):
ОК. Только скобок многовато)

2022-10-04 12:44 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_5.py
> +if my_choice == "1":
Цикла здесь нет. Проверить, закрыт ли файл, можно по значению атрибута fw.closed (если True - значит, закрыт).
Но если Вы используете менеджер контекста, может быть уверены, что файл закрылся)

2022-10-04 12:45 UTC, IlyaOrlov requested changes
Всё хорошо. Осталась пара небольших комментариев/пожеланий.

2022-10-04 12:45 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_5.py
> +fo = open("my_file.txt", "r")
Тогда уж менеджер контекста стоит применить и здесь.

2022-10-04 13:45 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_5.py
> +if my_choice == "1":
Хотелось проверить,  правильно ли применен менеджер контекста)

2022-10-04 13:46 UTC, natalishulgina commented on Practice/ShulginaN/Lec_5/task_4.py
> +        for m in range((len(ls[i]))):
но без них код работать не будет?) значит код плохой?)

2022-10-06 07:34 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_5/task_4.py
> +        for m in range((len(ls[i]))):
Ну я же не предлагаю ВСЕ скобки убрать. Но одна пара скобок здесь лишняя.
Вот так должно быть: for m in range(len(ls[i]))

2022-10-06 07:36 UTC, IlyaOrlov reviewed
Всё ОК. Только вопрос со скобками надо порешать.

2022-10-07 18:20 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-10-07 18:20 UTC, merged