text
IlyaOrlov/PythonCourse2.0_August22 pull request #70
Opened 2022-10-01 20:39 UTC by Ibryanova

тест

2022-10-02 17:01 UTC, IlyaOrlov reviewed
Тест пройден)

2022-10-03 22:16 UTC, Ibryanova commented
Илья, здравствуйте. По ошибке загрузила все свои файлы, которые я по лекциям делаю, не смотрите на них, пожалуйста. Я делаю все это по ночам((
К проверке хотела только файлы: home_lec5_task_1.py, home_lec5_task_2.py,home_lec5_task_3.py,home_lec5_task_5.py, в последнем не пойму, что у меня в файлом

2022-10-04 13:00 UTC, IlyaOrlov requested changes
Оставил замечания по указанным файлам. Чтоб не загружать на Гитхаб лишнего, нужно файлы, не предназначенные для публикации, поместить в отдельную папку и и через PyCharm сделать для этой папки Add to .gitignore

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_1.py
> +        min = i
min - имя стандартной функций, не стоит использовать его для именования своих переменных.

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_1.py
> +    return arr
Вопрос на понимание: имеет ли смысл возвращать тот же arr, который мы и так меняем в данной функции?

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_2.py
> +        if lst[i] in lst[:i:]:
Срез - это фактически новый список. Операция in для списка выполняется не так быстро, как для set. Поэтому здесь лучше складывать просмотренные элементы во вспомогательный set. И смотреть повторения в нём.

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_3.py
> +for i in d:
Чтоб потом не обращаться к значению элементу через d[i], можно получать его сразу, если обходить словарь через for i, val in d.items()

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_5.py
> +f_out = open(FILENAME, 'r')
Открывая файл, мы загружаем его в память. Когда потом мы переиспользуем переменную f_out для переоткрытого файла (даже того же самого), новый файл загружается в память, но и старый никуда не девается (занимает память, а обратиться к нему уже нельзя). 
Поэтому до строки 10 нужно сперва закрыть f_out.

2022-10-04 13:00 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_5.py
> +if x == '1':
Код в ветках if и else отличается одной строкой. Нельзя ли как-то оптимизировать алгоритм, вынеся что-нибудь из блока условного оператора?

2022-10-05 22:26 UTC, Ibryanova commented
Илья, 4 задание по 5 лекции мне тяжело дается, признаюсь делала не без помощи. Сложность моя в написании условии. Я смысл понимаю, а вот выдать в код мне сложно(что делать?

2022-10-06 11:35 UTC, IlyaOrlov requested changes
Остались ещё замечания.
Чтоб проще воплощать понимание в коде, надо тренироваться, как бы банально это ни звучало.
Как при изучении иностранного языка. На лекциях мы фактически изучаем грамматику и пополняем словарный запас. Но чтоб составлять из слов корректные предложения - надо практиковаться, порешать больше простых задачек.

2022-10-06 11:35 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_3.py
> +    s = s.replace(str(i), str(d[i]))
ОК. Но value же и использовать нужно: s = s.replace(str(i), str(value))

2022-10-06 11:35 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_2.py
> +       if num[i] in lst1:
Доступ к глобальной переменной из функции - не лучшее решение. lst1 нигде не требуется, кроме как в этой функции. Соответственно и объявлять ее нужно здесь.
Да, и lst1 (намек на list) - не лучшее имя для множества (set).

2022-10-06 11:35 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_2.py
> +           print({num[i]})
Фигурные скобки лишние.

2022-10-06 11:35 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec5_task_1.py
> +        arr[num], arr[i] = arr[i], arr[num]
Стоит проверить, что num не равно i, чтоб не переставлять одно и то же число.

2022-10-07 19:13 UTC, IlyaOrlov requested changes
ОК. Остались замечания по home_lec5_task_5.py и вопрос по home_lec5_task_1.py

2022-10-08 18:45 UTC, Ibryanova commented
комменты оставила, задания поправила

2022-10-09 09:44 UTC, IlyaOrlov requested changes
Остались три небольших замечания и один вопрос.

2022-10-09 09:44 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec7_task_1.py
> +class Tanks():
Раз нет родительского класса, то скобки указывать ни к чему.

2022-10-09 09:44 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec7_task_2.py
> +class Duck():
Раз нет родительского класса, то скобки указывать ни к чему.

2022-10-09 09:44 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec7_task_3.py
> +                f.close()
Раз мы применяем ```with open(self.filepath, 'r') as f:```, то явно закрывать файл не нужно. with сам обеспечит его закрытие.
Аналогично в стр.31

2022-10-09 21:51 UTC, IlyaOrlov reviewed
Замечаний больше нет. Но вопрос по [home_lec5_task_1.py](https://github.com/IlyaOrlov/PythonCourse2.0_August22/pull/70/files#diff-e2fade4e8cf71468eb885fb19c1ce4395c7928a18a2c1c441a657ad962914b72) остался: имеет ли смысл возвращать тот же arr, который мы и так меняем в функции?

2022-10-10 12:54 UTC, Ibryanova commented
мы проводили сортировку массива использую функ sort(arr), для завершения функ прописываем return, оператор return вернул значение выполненной ф-ции -- отсортированный массив

2022-10-10 13:00 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-10 13:00 UTC, merged