Lukichev i
IlyaOrlov/PythonCourse2.0_August22 pull request #71
Opened 2022-10-02 10:24 UTC by NazGuJl

2022-10-02 17:08 UTC, IlyaOrlov requested changes
ОК. Есть небольшие замечания и вопрос.

2022-10-02 17:08 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_1.py
> +class Tank():
Скобки здесь лишние, т.к. родительских классов у танка нет.

2022-10-02 17:08 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_1.py
> +        class_tank = ['Легкий танк', 'Средний танк', 'Тяжелый танк']
А вот этот набор лучше сделать кортежем и полем класса Tank, чтоб не пересоздавать при каждом вызове ```__init__```.

2022-10-02 17:08 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_2.py
> +    color = ('Серый')
А почему в скобках?

2022-10-02 17:08 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_2.py
> +     print('Кря кря!')
Слева пробелов не хватает.

2022-10-02 17:08 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_7/Lec_7_task_2.py
> +        print("I'm not ready yet")
Вопрос на понимание. Если предполагается, что solve_task у родителя будет со временем меняться, дополняться, что можно предусмотреть, чтоб при этом не переписывать методы дочерних классов (в частности класса Pupil), чтоб они автоматически подхватывали изменения в solve_task родителя?

2022-10-04 13:39 UTC, IlyaOrlov requested changes
ОК. Оставил несколько замечаний.

2022-10-04 13:39 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_1.py
> +    def my_tank(cls):
Этот метод не несёт в себе никакого смысла, т.к. class_tank и так принадлежит классу Tank.
А вот ```__init__``` из предыдущей редакции был бы очень кстати:
```python
    def __init__(self, my_tank):
        self.my_tank = self.class_tank[my_tank]
```
Затем создаём танк по выбору пользователя:
tank1 = Tank(tank)
И выводим тип танка на экран:
print(tank1.my_tank)

2022-10-04 13:39 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_6/Lec_6_task_3.py
> +        self.filepath = tempfile.mktemp()
Должен ли filepath быть доступен вне класса WrapStrToFile?

2022-10-04 13:39 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_7/Lec_7_task_3.py
> +            for _ in cls.option_lst:
Раз мы используем переменную цикла, то имя ```_``` ей уже не подходит.

2022-10-04 13:39 UTC, IlyaOrlov commented on Practice/LukichevI/Lec_7/Lec_7_task_3.py
> +    def quantity_cash(self):
Раз это обычный метод, не стоит называть его так же, как property в стр.9

2022-10-04 14:47 UTC, NazGuJl commented on Practice/LukichevI/Lec_7/Lec_7_task_3.py
> +            for _ in cls.option_lst:
Нет не должен, так как по условиям задачи мы используем метод @property, а следовательно напрямую обращаться  к _filepath не можем. Внес изменения в файл.

2022-10-05 07:23 UTC, NazGuJl commented on Practice/LukichevI/Lec_6/Lec_6_task_3.py
> +        self.filepath = tempfile.mktemp()
Нет не должен, так как по условиям задачи мы используем метод https://github.com/Property, а следовательно напрямую обращаться к _filepath не можем. Внес изменения в файл.

2022-10-06 10:13 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-06 10:13 UTC, merged