Задание 1 лекции 8
IlyaOrlov/PythonCourse2.0_August22 pull request #73
Opened 2022-10-04 21:32 UTC by Kuduzo

2022-10-06 10:57 UTC, IlyaOrlov requested changes
ОК. Оставил несколько замечаний.

2022-10-06 10:57 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 08/task01.py
> +        if res[-1] == "\n":
Как я понял, это чтоб лишних пустых строк при выводе не было? ОК, но вообще это уже не проблема итератора. И что будет, если файл пустой?

2022-10-06 10:57 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 08/task01.py
> +        return res
А цикл for с таким итератором будет работать?
Чтоб работал и не зацикливался бесконечно, надо предусмотреть выбрасывание StopIteration, когда файл закончился.

2022-10-06 10:57 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 08/task01.py
> +        self._f = f
Лучше сюда передавать имя файла, чтоб итератор сам его открывал и сам следил за закрытием. А поскольку в этом случае менеджер контекста не получится использовать, есть лайфхак: открываем файл здесь в ```__init__```, а закрываем в магическом методе ```__del__``` - этот метод вызовется для экземпляра класса MyIterator при закрытии программы что бы ни произошло.

2022-10-06 10:57 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 08/task02.py
> +    x = (i[:-1] for i in f.readlines())
readlines возвращает список строк файла, поэтому никакого выигрыша по памяти мы здесь не получим

2022-10-06 20:52 UTC, Kuduzo commented
Нужна небольшая помощь в заднии 1 лек 8.
Не получается никак вытянуть git push
для команд git clone не получается вытянуть именно адрес. Пока что приходится цепляться за след символ за ним, но это неправильно.

2022-10-06 21:15 UTC, Kuduzo commented
Сделал в первом задании все команды. Единственная проблема это с выводом просто push. 
Если делать для Push то он перехватывает push --set....... Хотел бы попросить подсказать как поступить.

2022-10-07 19:09 UTC, IlyaOrlov commented
> Сделал в первом задании все команды. Единственная проблема это с выводом просто push. Если делать для Push то он перехватывает push --set....... Хотел бы попросить подсказать как поступить.

Можно применять дополнительный поиск конкретно для git push. Можно написать более общее выражение, типа '(git [^а-я"\n)]+("[а-яА-Я ]+")?)' и немного отредактировать результат.

2022-10-07 19:10 UTC, IlyaOrlov requested changes
С заданием по re и git - всё ОК. А по итератору остались замечания.

2022-10-07 19:10 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec 08/task01.py
> +        if temp != "":
А как temp может оказаться пустой строкой, если она только что (в стр.11) проинициализирована пробелом.
На самом деле здесь проще вместо break сделать return res, а вместо return res - raise StopIteration.

2022-10-07 19:51 UTC, Kuduzo commented
Не понимаю что делает выражение ("[а-яА-Я ]+"), для чего внутри ковычки сделаны.  И в (git [^а-я"\n)]  почему после n стоит закрывающая скобка, у нас получается кол-во закрывающихся и открывающихся скобок не ровно во всей строке. Я думаю к пн большинство сделают это задание, сможете объяснить как понимать ваше выражение?

2022-10-07 20:06 UTC, IlyaOrlov commented
> Не понимаю что делает выражение ("[а-яА-Я ]+"), для чего внутри ковычки сделаны. И в (git [^а-я"\n)] почему после n стоит закрывающая скобка, у нас получается кол-во закрывающихся и открывающихся скобок не ровно во всей строке. Я думаю к пн большинство сделают это задание, сможете объяснить как понимать ваше выражение?

В квадратных скобках **[^а-я"\n)]** просто перечисляются НЕдопустимые символы: **а-я, ", \n, )** (если бы не было **^** вначале, то это были бы допустимые символы).
Выражение **[а-яА-Я ]+** означает 1 или больше повторений символов внутри квадратных скобок. А внутри скобок просто все буквы перечислены. Т.е. фактически это выражение совпадет с любым набором букв.

2022-10-09 08:14 UTC, IlyaOrlov approved these changes
Отлично!

2022-10-09 08:14 UTC, merged