Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #77
Opened 2022-10-11 18:13 UTC by natalishulgina

Задачи по лекции 8

2022-10-12 09:49 UTC, IlyaOrlov requested changes
Хорошо, но стоит учесть некоторые нюансы в итераторе для файла.

2022-10-12 09:49 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_8/task_1.py
> +            if my_str != "":
Идея верная, но порядок проверок надо скорректировать, чтоб учесть следующее:
1. если файл непустой, но не содержит символ параграфа - все равно же что-то должно вернуться.
2. если my_str равен символу параграфа, его к res добавлять не нужно

2022-10-12 19:19 UTC, natalishulgina commented on Practice/ShulginaN/Lec_8/task_1.py
> +            if my_str != "":
Спасибо, внесла корректировки. Теперь символ не попадает и печатается весь текст из файла.

2022-10-14 09:21 UTC, IlyaOrlov requested changes
ОК. Один комментарий только остался.

2022-10-14 09:21 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_8/task_1.py
> +        if my_str != "":
Наверное, логичней здесь всё-таки проверять if res != ""

2022-10-14 09:27 UTC, natalishulgina commented on Practice/ShulginaN/Lec_8/task_1.py
> +        if my_str != "":
Исправила.

2022-10-14 09:27 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-14 09:27 UTC, merged