Esafonova
IlyaOrlov/PythonCourse2.0_August22 pull request #8
Opened 2022-08-31 19:20 UTC by SafonovaEkaterina

2022-09-01 13:05 UTC, IlyaOrlov requested changes
Всё замечательно! Есть небольшие замечания.

2022-09-01 13:05 UTC, IlyaOrlov commented on Practice/esafonova/pep8task.py
> +            # Лишняя или недостающая скобка
Так лишняя или недостающая? И в какой строке: предыдущей или следующей?

2022-09-01 13:05 UTC, IlyaOrlov commented on Practice/esafonova/pep8task.py
> +          mp3s = [] # Нарушение табуляции
Здесь и в строке 31 лучше говорить о нарушении уровня вложенности или количества отступов, т.к. "нарушение табуляции" скорее предполагает неправильное использование символа табуляции.

2022-09-01 13:05 UTC, IlyaOrlov commented on Practice/esafonova/tasksq.py
>  def square(r):
Пустая строка между блоком импортов и блоком определений была совсем не лишней. Скорее наоборот: PEP8 требует каждый такой блок обособлять двумя пустыми строками.

2022-09-01 13:05 UTC, IlyaOrlov commented on Practice/esafonova/pep8task.py
> +    def rename(self, dirname, output): # Наименование dir_name через подчеркивание
Ошибки вида dirname вместо dir_name, строго говоря, подпадают под требования к читабельности кода. Но на практике, если слово легко читается и его смысл понятен даже при слитном написании, то разделять слова нижним подчеркиванием необязательно. Вот если бы было что-то типа directoryname - тут да, без разделения буквы сливаются.

2022-09-05 16:43 UTC, SafonovaEkaterina commented
Добрый день. Исправлено.

2022-09-05 16:46 UTC, SafonovaEkaterina commented on Practice/esafonova/pep8task.py
> +            # Лишняя или недостающая скобка
+

2022-09-05 16:46 UTC, SafonovaEkaterina commented on Practice/esafonova/pep8task.py
> +          mp3s = [] # Нарушение табуляции
+

2022-09-05 16:46 UTC, SafonovaEkaterina commented on Practice/esafonova/tasksq.py
>  def square(r):
+

2022-09-05 16:46 UTC, SafonovaEkaterina commented on Practice/esafonova/pep8task.py
> +    def rename(self, dirname, output): # Наименование dir_name через подчеркивание
+

2022-09-06 12:52 UTC, IlyaOrlov approved these changes
Отлично!

2022-09-06 12:52 UTC, merged