Lec 9
IlyaOrlov/PythonCourse2.0_August22 pull request #80
Opened 2022-10-14 13:52 UTC by Tetrackon

2022-10-14 20:09 UTC, IlyaOrlov requested changes
Оставил некоторые замечания.

2022-10-14 20:09 UTC, IlyaOrlov commented on Practice/KharinB/Task 1 Lec 9.py
> +        a = re.findall(r"git [\w]+ ?[!-~]* *[A-z]+ *[\"]{1}[\D]+[\"]{1}", st) or re.findall(r"git [\w]+ ?[!-~]* *[A-z]+", st)
ОК, но строка длинновата, а про PEP8 забывать не стоит.

2022-10-14 20:09 UTC, IlyaOrlov commented on Practice/KharinB/Task 2 Lec 9.py
> +print(calculator_days())
У меня получился такой расчёт (кстати, ожидаемый формат ввода даты, лучше указывать сразу, а не только после ошибочного ввода):
Введите дату начала отсчёта: 16/10/2022
Введите дату окончания отсчёта: 22/10/2022
**-1**

2022-10-14 20:09 UTC, IlyaOrlov commented on Practice/KharinB/Task 1 Lec 10.py
> +lst = ["10", "5", "a", "3", "b"]
ОК. Но всё то же самое можно было сделать в одну строку одним списковым выражением.

2022-10-14 20:09 UTC, IlyaOrlov commented on Practice/KharinB/Task 3 Lec 9.py
> +            if res_dir > 120:
Имеет смысл сначала проверять файлы, т.к. если файлы в папке остались - удалять ее не следует.

2022-10-16 15:37 UTC, Tetrackon commented on Practice/KharinB/Task 2 Lec 9.py
> +print(calculator_days())
Исправил, но кажется намудрил...

2022-10-16 15:38 UTC, Tetrackon commented on Practice/KharinB/Task 1 Lec 10.py
> +lst = ["10", "5", "a", "3", "b"]
Не совсем понял что имеется ввиду... весь код можно было в одну строку?

2022-10-16 15:38 UTC, Tetrackon commented on Practice/KharinB/Task 3 Lec 9.py
> +            if res_dir > 120:
Сделал

2022-10-16 15:38 UTC, Tetrackon commented on Practice/KharinB/Task 1 Lec 9.py
> +        a = re.findall(r"git [\w]+ ?[!-~]* *[A-z]+ *[\"]{1}[\D]+[\"]{1}", st) or re.findall(r"git [\w]+ ?[!-~]* *[A-z]+", st)
исправил

2022-10-16 17:26 UTC, IlyaOrlov commented on Practice/KharinB/Task 1 Lec 10.py
> +lst = ["10", "5", "a", "3", "b"]
Да, например так:
```python
new_lst = [x*x for i in lst if i.isdecimal() and (x := int(i)) % 5 == 0]
```

2022-10-16 17:40 UTC, IlyaOrlov requested changes
Остались замечания, в первую очередь, по стилю и читабельности.

2022-10-16 17:40 UTC, IlyaOrlov commented on Practice/KharinB/Task 2 Lec 9.py
> +def calculator_days(s = "18/9/2022", f = "22/10/2022" ):
При указании значений по умолчанию пробелы вокруг = [не нужны](https://peps.python.org/pep-0008/#pet-peeves:~:text=Don%E2%80%99t%20use%20spaces%20around%20the%20%3D%20sign%20when%20used%20to%20indicate%20a%20keyword%20argument%2C%20or%20when%20used%20to%20indicate%20a%20default%20value%20for%20an%20unannotated%20function%20parameter%3A).

2022-10-16 17:40 UTC, IlyaOrlov commented on Practice/KharinB/Task 2 Lec 9.py
> +        if start[1]>4:
В стр.34 и 35 нужны пробелы вокруг > (см. [PEP8](https://peps.python.org/pep-0008/#pet-peeves:~:text=Always%20surround%20these%20binary%20operators%20with%20a%20single%20space%20on%20either%20side))

2022-10-16 17:40 UTC, IlyaOrlov commented on Practice/KharinB/Task 2 Lec 9.py
> +    start = vvod("Введите дату начала отсчёта(День/Месяц/Год): ", 0, s)
Лучше, когда функция выполняет какую-то одну задачу. Если функция должна посчитать количество рабочих дней между датами, не стоит нагружать её обязанностью по вводу этих дат. Тогда функцию будет удобно импортировать и использовать для предопределённых данных и автотестов.

2022-10-16 17:40 UTC, IlyaOrlov commented on Practice/KharinB/Task 2 Lec 9.py
> +        finish = vvod("Введите дату окончания отсчёта(День/Месяц/Год): ", 0, f)
Чтоб код был понятней, лучше не использовать start и finish, как списки, элементы которых совсем не очевидны. Раз vvod возвращает несколько значений, лучше получить их как 
```python
start_date, start_day = vvod(...)
finish_date, finish_day = vvod(...)
```

2022-10-16 17:40 UTC, IlyaOrlov commented on Practice/KharinB/Task 3 Lec 9.py
> +        for d in lst_dir:
Здесь та же проблема, что и в задаче с датами. Что такое d[0], d[1] и d[2]? Лучше использовать осмысленные имена для переменных, указывающих на папки, файлы и т.д.

2022-10-21 19:44 UTC, IlyaOrlov commented on Practice/KharinB/Lec 11/Task 1.py
> +            end_iter = start//2+1
Достаточно даже только до квадратного корня из start проверять.

2022-10-21 19:45 UTC, IlyaOrlov commented on Practice/KharinB/Lec 11/Task 1.py
> +    # Увеличил числа в 10 раз, потому что иначе не показательно... процессы создаются дольше, чем функция выполняется
Верное замечание!

2022-10-21 19:46 UTC, IlyaOrlov commented on Practice/KharinB/Lec 11/Task 2.py
> +# с точки зрения полезности - программа не очень, но я подумал что раз в условиях задачи идёт речь именно о параллельном
Тоже верно подмечено!

2022-10-21 19:48 UTC, IlyaOrlov commented on Practice/KharinB/Lec 11/Task 3.py
> +    print(f"Номер потока {num}") # Номер подойдёт для персональных данных?
Вполне подойдет. num - локальная переменная внутри thread_info - создается на стеке, следовательно, у каждого потока это будет своя переменная.

2022-10-21 19:49 UTC, IlyaOrlov requested changes
По процессам/потокам всё супер! Надо только старые замечания поправить к предыдущим заданиям.

2022-10-22 21:26 UTC, Tetrackon commented on Practice/KharinB/Task 2 Lec 9.py
> +def calculator_days(s = "18/9/2022", f = "22/10/2022" ):
Исправил

2022-10-22 21:26 UTC, Tetrackon commented on Practice/KharinB/Task 2 Lec 9.py
> +        if start[1]>4:
Исправил

2022-10-22 21:27 UTC, Tetrackon commented on Practice/KharinB/Task 2 Lec 9.py
> +    start = vvod("Введите дату начала отсчёта(День/Месяц/Год): ", 0, s)
Вынес подсчёт в отдельную функцию calculation

2022-10-22 21:27 UTC, Tetrackon commented on Practice/KharinB/Task 2 Lec 9.py
> +        finish = vvod("Введите дату окончания отсчёта(День/Месяц/Год): ", 0, f)
Исправил

2022-10-22 21:27 UTC, Tetrackon commented on Practice/KharinB/Task 3 Lec 9.py
> +        for d in lst_dir:
Исправил. Прошу прощения, буду теперь давать более осмысленные имена переменным.

2022-10-23 08:45 UTC, IlyaOrlov commented on Practice/KharinB/Task 3 Lec 9.py
> +        for d in lst_dir:
ОК. Можно было короче, сразу распаковывая d по переменным: for main_folder, folders, files in lst_dir:

2022-10-23 08:51 UTC, IlyaOrlov requested changes
Всё замечательно! Особенно работа с процессами и распределение кода по функциям в задаче по сетевому программированию.
Надо только оставшийся комментарий к Lec 11/Task 1.py применить (в контрольной пригодится;))

2022-10-23 11:29 UTC, Tetrackon commented
> Всё замечательно! Особенности работы с процессами и решениями по функции в задаче по сетевому программированию. Надо только оставшийся комментарий к Lec 11/Task 1.py применить (в контрольной пригодится;))

Добрый день! Исправил подсчёт до квадратного корня (ну и название переменной исправил, но это не на что не влияет). Имелось ввиду именно это?

2022-10-23 15:37 UTC, IlyaOrlov approved these changes
Да, всё верно. Отлично!

2022-10-23 15:38 UTC, merged