Ogarbis
IlyaOrlov/PythonCourse2.0_August22 pull request #83
Opened 2022-10-15 12:16 UTC by Chipmunk77

Добрый день!
Задания лекции 10

2022-10-15 17:19 UTC, Chipmunk77 commented
Илья, я не придумала, как работать с файлом README в разрешении .md (как сослаться на него), поэтому сохранила текст в .txt. Объясните, пожалуйста, как правильно нужно сделать

2022-10-15 20:03 UTC, IlyaOrlov requested changes
ОК. Есть небольшие замечания.

2022-10-15 20:03 UTC, IlyaOrlov commented on Practice/GarbisO/lec9 t1.py
> +    pattern = re.compile(r"git [a-z]+")
Стоит расширить регулярное выражение, чтоб под него попадали не только git и название команды, но и аргументы.

2022-10-15 20:03 UTC, IlyaOrlov commented on Practice/GarbisO/lec9 t1.py
> +        print(res)
Если res получился пустой - выводить его не стоит.

2022-10-15 20:03 UTC, IlyaOrlov commented on Practice/GarbisO/lec9 t1.py
> +with open("README.txt", "r") as f:
README.md

2022-10-15 20:03 UTC, IlyaOrlov commented on Practice/GarbisO/lec10 t2.py
> +    match (input("Введите что-нибудь: ")):
Скобки вокруг input лишние

2022-10-17 21:01 UTC, IlyaOrlov commented
> Илья, я не придумала, как работать с файлом README в разрешении .md (как сослаться на него), поэтому сохранила текст в .txt. Объясните, пожалуйста, как правильно нужно сделать

Так а что мешает написать как есть: ```with open("README.md", "r") as f:```?
Если он находится на уровень выше - используем относительный путь ```with open(".../README.md", "r") as f:```

2022-10-17 21:02 UTC, IlyaOrlov requested changes
Остались ещё замечания.

2022-10-18 12:52 UTC, Chipmunk77 commented
Поняла, в чем моя ошибка с файлом READ.md. Она прям оч глупая...)

2022-10-19 12:22 UTC, IlyaOrlov commented on Practice/GarbisO/lec9 t1.py
> +        print(res)
OK. Но можно просто if not res:

2022-10-19 12:23 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-19 12:23 UTC, merged