text lec 8-1
IlyaOrlov/PythonCourse2.0_August22 pull request #84
Opened 2022-10-15 22:14 UTC by Ibryanova

2022-10-16 17:23 UTC, IlyaOrlov requested changes
Хорошо, но одно замечание всё же есть.

2022-10-16 17:23 UTC, IlyaOrlov commented on Practice/Ibryanova/VA_ibryanova/home_lec8_task_2.py
> +m = Man('Vladimir')
Ещё надо продемонстрировать, как решает задачи экземпляр Pupil.

2022-10-16 21:31 UTC, Ibryanova commented on Practice/Ibryanova/VA_ibryanova/home_lec8_task_2.py
> +m = Man('Vladimir')
поправила

2022-10-17 20:58 UTC, IlyaOrlov approved these changes
Отлично!

2022-10-17 20:58 UTC, merged