Shulgina branch
IlyaOrlov/PythonCourse2.0_August22 pull request #90
Opened 2022-10-21 19:32 UTC by natalishulgina

дз по 11 лекции

2022-10-21 20:20 UTC, IlyaOrlov requested changes
Оставил пару вопросов по мультипроцессингу.

2022-10-21 20:20 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_11/task_1.py
> +        for j in range(2, i**2):
Только проверять надо не до квадрата числа, а до квадратного корня из числа!

2022-10-21 20:20 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_11/task_1.py
> +# Замерить время исполнения каждого варианта и сравнить результаты.
Какой вывод? Кто быстрее и почему?

2022-10-21 22:26 UTC, natalishulgina commented on Practice/ShulginaN/Lec_11/task_1.py
> +        for j in range(2, i**2):
поправила)

2022-10-21 22:27 UTC, natalishulgina commented on Practice/ShulginaN/Lec_11/task_1.py
> +# Замерить время исполнения каждого варианта и сравнить результаты.
В данном случае, через потоки и обычную функцию быстрее, чем через процессы. Потому, что для запуска процесса затрачивается больше времени (у процесса все свое - сегмент кода, сегмент данных, стек), чем для запуска потока (у потоков же разные только стек) и выполнение обычной функции.

2022-10-22 07:55 UTC, IlyaOrlov commented on Practice/ShulginaN/Lec_11/task_1.py
> +# Замерить время исполнения каждого варианта и сравнить результаты.
Согласен

2022-10-22 07:55 UTC, IlyaOrlov approved these changes
Всё отлично!

2022-10-22 07:55 UTC, merged