Задание 1 лекции 15
IlyaOrlov/PythonCourse2.0_August22 pull request #91
Opened 2022-10-22 20:40 UTC by Kuduzo

2022-10-22 20:51 UTC, IlyaOrlov requested changes
Все ОК. Оставил пару небольших комментариев.

2022-10-22 20:51 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/test_task01.py
> +        assert e.type == SystemExit
with pytest.raises(SystemExit) уже проверяет тип исключения

2022-10-22 20:51 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/test_task01.py
> +        assert (to_roman(1) == "I")
Если assert используете со скобками, то пробел сразу после assert не нужен

2022-10-22 21:06 UTC, Kuduzo commented on Practice/RybnikovS/Lec15/test_task01.py
> +        assert e.type == SystemExit
Имеете ввиду нужно только проверить код ошибки?

2022-10-22 21:37 UTC, Kuduzo commented
Забыл загрузить 3 задание 11 лекции.

2022-10-23 08:55 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/test_task01.py
> +        assert e.type == SystemExit
Да. Ну и в test_more_than(self): - то же самое. 
Тут еще код получился немного искусственным, т.к. в реальности to_roman выбрасывала бы ValueError или IndexError, и в тесте мы просто ориентировались бы на перехват этих типов исключений.

2022-10-23 09:02 UTC, IlyaOrlov requested changes
Всё замечательно! Остались комментарии по мелочам.

2022-10-23 09:02 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/task02.py
> +one = Money(50, 20)
Чтоб этот код не мешался в тесте, хорошо бы его по ```if __name__ == "__main__":``` убрать.

2022-10-23 09:02 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/test_task01.py
> +        assert e.value.code == 666
Стоит придерживаться единого стиля: либо везде assert со скобками, либо везде без них.

2022-10-23 09:02 UTC, IlyaOrlov commented on Practice/RybnikovS/Lec15/test_task02.py
> +    def test_add(self):
Сами тесты хороши, замечания только по стилю: лишний пробел между скобкой и assert, сравнение c True/False стоит делать через is (см. [PEP8](https://peps.python.org/pep-0008/#:~:text=Don%E2%80%99t%20compare%20boolean%20values%20to%20True%20or%20False%20using%20%3D%3D))

2022-10-23 13:16 UTC, Kuduzo commented
Исправлено

2022-10-23 15:39 UTC, IlyaOrlov approved these changes
Теперь всё отлично!

2022-10-23 15:39 UTC, merged